const {randomUUID}=require('node:crypto');
const Subscription=require('../models/subscriptionModel');
module.exports=async({pool,url,request,check,reject,createUser,shop,admin,reception})=>{
  await pool.query(`UPDATE subscription_plans SET name=CASE WHEN code='barberbook' THEN 'Mirror Basic' ELSE 'Mirror Plus' END,
    features=CASE WHEN code='barberbook_plus' THEN '{"publicWebsite":false,"onlineBooking":false,"inventoryAlerts":true,"telegramDigest":true}'::jsonb ELSE '{"telegramDigest":false}'::jsonb END,
    limits=CASE WHEN code='barberbook_plus' THEN '{"staff":50,"dailyCustomers":50}'::jsonb ELSE '{"staff":8,"dailyCustomers":20}'::jsonb END
    WHERE code IN ('barberbook','barberbook_plus')`);
  const publicRequest=(route,body)=>fetch(url+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
  const signup={ownerName:'Trial Owner',ownerPhone:'0912345688',email:'trial-owner@test.local',password:'TestTrial123!',shopName:'Trial Studio',role:'platform_admin',shopId:shop,subscription_status:'active'};
  const signed=await publicRequest('/auth/signup',signup);const session=await signed.json();
  check(signed.status===201&&session.token&&session.expiresIn===3600&&session.user.role==='admin'&&session.user.shopId!==shop,'Public signup creates an owner and separate tenant with a one-hour session, ignoring supplied privileged fields');
  const tenant=session.user.shopId,owner=session.user.id;
  const trial=(await pool.query('SELECT * FROM shops WHERE id=$1',[tenant])).rows[0];
  check(new Date(trial.trial_ends_at)-new Date(trial.trial_started_at)===7*86400000&&trial.plan_code==='barberbook_plus'&&trial.subscription_status==='trial','Trial grants exactly seven days of Plus from signup');
  check(!trial.onboarding_completed_at&&!trial.website_enabled,'A new shop needs setup and public website opt-in');
  const shopsBefore=(await pool.query('SELECT COUNT(*)::int AS n FROM shops')).rows[0].n;
  check((await publicRequest('/auth/signup',{...signup,email:'TRIAL-OWNER@test.local',shopSlug:'anotherstudio'})).status===400,'Email reuse cannot create a new trial, regardless of case');
  check((await pool.query('SELECT COUNT(*)::int AS n FROM shops')).rows[0].n===shopsBefore,'Failed signup leaves no orphan shop');
  const sameName=await publicRequest('/auth/signup',{...signup,email:'another-owner@test.local',ownerPhone:'0912345689',shopSlug:'../../admin'});
  const sameNameSession=await sameName.json();
  check(sameName.status===201&&sameNameSession.user.shop.slug!==trial.slug&&/^[a-z]+$/.test(sameNameSession.user.shop.slug),'Signup creates a safe unique workspace address automatically and ignores a supplied address');
  const setup={team:[{name:'Trial Barber',phone:'0912345678',password:'TestBarber123!',role:'barber'},{name:'Trial Desk',phone:'0912345679',password:'TestDesk123!',role:'receptionist'}],services:[{name:'Trial haircut',price:180,duration:30}],websiteEnabled:true,address:'Test address',phone:'0000000000'};
  const invalidPhone=await request('/admin/onboarding',owner,'admin',tenant,'POST',{...setup,team:[{...setup.team[0],phone:'barber'},setup.team[1]]});
  const phoneProblem=await invalidPhone.json();
  check(invalidPhone.status===400&&phoneProblem.step===0&&phoneProblem.field==='team.0.phone'&&phoneProblem.error.includes('Trial Barber'),'Invalid phone identifies the team member to correct');
  const duplicatePhone=await (await request('/admin/onboarding',owner,'admin',tenant,'POST',{...setup,team:[setup.team[0],{...setup.team[1],phone:setup.team[0].phone}]})).json();
  check(duplicatePhone.step===0&&duplicatePhone.field==='team.1.phone','Duplicate staff phone returns a correctable team-field error');
  check((await request('/admin/onboarding',owner,'admin',tenant,'POST',{...setup,team:[{...setup.team[0],role:'platform_admin'}]})).status===400,'Onboarding cannot create a privileged team account');
  check((await request('/admin/onboarding',owner,'admin',tenant,'POST',{...setup,services:[{name:'Invalid',price:-1}]})).status===400,'Invalid setup is rejected before creating staff');
  check((await pool.query('SELECT COUNT(*)::int AS n FROM users WHERE shop_id=$1',[tenant])).rows[0].n===1,'Invalid onboarding leaves the tenant unchanged');
  await pool.query(`UPDATE subscription_plans SET limits='{"staff":2}'::jsonb WHERE code='barberbook_plus'`);
  check((await request('/admin/onboarding',owner,'admin',tenant,'POST',setup)).status===400,'Onboarding enforces the package account limit including the owner');
  await pool.query(`UPDATE subscription_plans SET limits='{"staff":50}'::jsonb WHERE code='barberbook_plus'`);
  check((await request('/admin/onboarding',owner,'admin',tenant,'POST',setup)).status===200,'Owner can finish guided shop setup');
  await request('/admin/onboarding',owner,'admin',tenant,'POST',setup);
  check((await pool.query('SELECT COUNT(*)::int AS n FROM users WHERE shop_id=$1',[tenant])).rows[0].n===3,'Onboarding retry does not duplicate team accounts');
  const till=(await pool.query('SELECT * FROM payment_accounts WHERE shop_id=$1',[tenant])).rows[0];
  check(till.method==='cash'&&till.created_by===owner,'Onboarding creates the shop cash till');
  const [barber,desk]=(await pool.query("SELECT id,role FROM users WHERE shop_id=$1 AND role<>'admin' ORDER BY role",[tenant])).rows;
  const phoneLogin=await publicRequest('/auth/login',{identifier:'0912345678',password:'TestBarber123!'});
  check(phoneLogin.status===200&&(await phoneLogin.json()).user.role==='barber','Workspace staff sign in with their Ethiopian phone number and password');
  const credentialUpdate=await request(`/admin/users/${desk.id}/credentials`,owner,'admin',tenant,'PUT',{phone:'0912345680',password:'ChangedDesk123!'});
  const changedLogin=await publicRequest('/auth/login',{identifier:'0912345680',password:'ChangedDesk123!'});
  check(credentialUpdate.status===200&&changedLogin.status===200&&(await changedLogin.json()).user.role==='receptionist','Owners can move existing workspace staff to phone sign-in without replacing their account');
  const ownUsers=await (await request('/admin/users',owner,'admin',tenant)).json();
  check(ownUsers.every(u=>u.shop_id===tenant)&&!ownUsers.some(u=>u.id===admin),'Owner can see only their own team');
  check((await request('/platform/overview',owner,'admin',tenant)).status===403,'Shop owner cannot access platform administration');
  check((await request('/admin/shop',owner,'platform_admin',null)).status===401,'JWT claims cannot elevate a stored shop owner to platform admin');
  check((await publicRequest('/public/shop')).status===404&&(await publicRequest('/services')).status===404,'Public requests require a shop address instead of falling back to the first tenant');
  check(!(await pool.query('SELECT website_enabled FROM shops WHERE id=$1',[tenant])).rows[0].website_enabled,'An older setup form cannot turn on the trial website');
  check(session.user.features.publicWebsite===false&&session.user.features.onlineBooking===false,'Trial session does not advertise website or booking access');
  check((await request('/admin/website-request',owner,'admin',tenant,'POST',{})).status===404,'Website request workflow is not exposed in the shop workspace');
  check((await request('/admin/shop/website',owner,'admin',tenant,'PUT',{enabled:true})).status===404,'Website publishing is not exposed in the shop workspace');
  await pool.query('UPDATE shops SET website_enabled=true WHERE id=$1',[tenant]);
  check((await publicRequest('/public/shop?shop=trialstudio')).status===404,'Legacy website flag cannot expose a trial shop');
  check((await publicRequest('/barber/barbers?shop=trialstudio')).status===404&&(await publicRequest('/services?shop=trialstudio')).status===404,'Trial public barber and service lists are unavailable');
  check((await publicRequest('/appointments/book?shop=trialstudio',{})).status===404&&(await publicRequest('/appointments/barber/'+barber.id+'?shop=trialstudio')).status===404,'Trial blocks public booking creation and availability');
  await pool.query('UPDATE shops SET website_enabled=false WHERE id=$1',[tenant]);
  const boundary={...trial,trial_ends_at:'2026-09-21T10:00:00.000Z'};
  check(Subscription.access(boundary,new Date('2026-09-21T09:59:59.999Z')).canOperate&&!Subscription.access(boundary,new Date('2026-09-21T10:00:00.000Z')).canOperate,'Trial expires exactly at the seven-day boundary');
  await pool.query("UPDATE shops SET trial_ends_at=NOW()-INTERVAL '1 second' WHERE id=$1",[tenant]);
  check((await request('/admin/owner/report',owner,'admin',tenant)).status===402,'An already-signed-in owner loses operational access when the trial expires');
  check((await request('/receptionist/desk',desk.id,'receptionist',tenant)).status===402,'Expired trial blocks reception operations');
  check((await request('/barber/appointments',barber.id,'barber',tenant)).status===402,'Expired trial blocks barber operations');
  check((await request('/auth/me',desk.id,'receptionist',tenant)).status===200,'Expired staff can still refresh their account and receive the subscription status');
  const expiredStaffLogin=await publicRequest('/auth/login',{identifier:'0912345680',password:'ChangedDesk123!'});
  check(expiredStaffLogin.status===200&&(await expiredStaffLogin.json()).user.subscription.status==='trial_expired','Expired staff can sign in and receive a clear subscription-required state');
  check((await request('/services',owner,'admin',tenant)).status===402,'Optional-auth service endpoint also checks trial expiry');
  check((await publicRequest('/public/shop?shop=trialstudio')).status===404,'Expired trial takes the tenant public page offline');
  const expiredLogin=await publicRequest('/auth/login',{email:signup.email,password:signup.password});
  check(expiredLogin.status===200&&(await expiredLogin.json()).user.subscription.status==='trial_expired','Expired owners can still sign in to choose a paid package');
  check((await request('/admin/subscription',owner,'admin',tenant)).status===200,'Billing remains accessible after expiry');
  const platform=await createUser('SaaSPlatform','platform_admin',null);
  const accountResponse=await request('/platform/billing/accounts',platform,'platform_admin',null,'POST',{name:'Platform bank',method:'bank_transfer',reference:'TEST-PLATFORM-ACCOUNT',accountHolder:'Mirror test'});
  const account=await accountResponse.json();check(accountResponse.status===200,'Platform admin can configure receiving accounts');
  check((await request('/platform/billing/accounts',owner,'admin',tenant,'POST',{})).status!==200,'Shop owner cannot edit platform payment accounts');
  const body={action:'change',planCode:'barberbook',accountId:account.id,transactionReference:'TEST-TRIAL-1',requestKey:randomUUID(),expectedAmount:799,paymentConfirmed:true};
  check((await request('/admin/subscription',owner,'admin',tenant,'POST',{...body,requestKey:randomUUID(),receiptOmit:true})).status===400,'Subscription payment requires a transfer receipt screenshot');
  await pool.query(`UPDATE subscription_plans SET limits='{"staff":2}'::jsonb WHERE code='barberbook'`);
  check((await request('/admin/subscription',owner,'admin',tenant,'POST',body)).status===400,'Package purchase cannot bypass its team-size limit');
  await pool.query(`UPDATE subscription_plans SET limits='{"staff":8}'::jsonb WHERE code='barberbook'`);
  check((await request('/admin/subscription',owner,'admin',tenant,'POST',{...body,expectedAmount:1})).status===400,'Owner cannot submit an altered package price');
  const purchaseResponse=await request('/admin/subscription',owner,'admin',tenant,'POST',body),purchase=await purchaseResponse.json();
  check(purchaseResponse.status===200&&purchase.status==='pending','Transfer details enter the platform verification queue');
  check((await request('/admin/owner/report',owner,'admin',tenant)).status===402,'Submitting payment does not grant access before verification');
  const retried=await (await request('/admin/subscription',owner,'admin',tenant,'POST',body)).json();
  check(retried.id===purchase.id,'A payment-submission retry creates no duplicate request');
  check((await request('/admin/subscription',owner,'admin',tenant,'POST',{...body,requestKey:randomUUID()})).status===400,'Only one subscription payment may be pending per shop');
  check((await request('/platform/billing/requests/'+purchase.id,owner,'admin',tenant,'PUT',{decision:'approve',paymentVerified:true})).status!==200,'Owner cannot approve their own payment');
  check((await request('/platform/billing/requests/'+purchase.id,platform,'platform_admin',null,'PUT',{decision:'approve'})).status===400,'Platform approval requires verification confirmation');
  const approval=await request('/platform/billing/requests/'+purchase.id,platform,'platform_admin',null,'PUT',{decision:'approve',paymentVerified:true});
  const approvedBody=await approval.json();
  check(approval.status===200&&approvedBody.status==='approved','Verified payment activates the chosen package: '+JSON.stringify(approvedBody));
  const paidShop=(await pool.query('SELECT *,current_period_end::text AS current_period_end FROM shops WHERE id=$1',[tenant])).rows[0];
  await request('/platform/billing/requests/'+purchase.id,platform,'platform_admin',null,'PUT',{decision:'approve',paymentVerified:true});
  check((await pool.query('SELECT current_period_end::text AS end FROM shops WHERE id=$1',[tenant])).rows[0].end===paidShop.current_period_end,'Repeated approval does not extend the subscription twice');
  check(paidShop.plan_code==='barberbook'&&paidShop.subscription_status==='active'&&paidShop.current_period_end,'Basic purchase records a paid monthly period');
  check((await request('/admin/owner/report',owner,'admin',tenant)).status===200,'Paid owner regains the same workspace and records');
  check((await publicRequest('/public/shop?shop=trialstudio')).status===404,'Basic does not publish the Max website');
  check((await request('/admin/website-request',owner,'admin',tenant,'POST',{})).status===404,'Paid Basic also has no in-system website request workflow');
  check((await (await request('/admin/users',owner,'admin',tenant)).json()).length===3,'Package conversion preserves the shop team');
  const secondTenantResponse=await request('/admin/subscription',admin,'admin',shop,'POST',{...body,requestKey:randomUUID()});
  const secondTenantRequest=await secondTenantResponse.json();
  check(secondTenantResponse.status===200&&secondTenantRequest.status==='pending','Payment submissions remain isolated per tenant without a reference-number requirement');
  await request('/platform/billing/requests/'+secondTenantRequest.id,platform,'platform_admin',null,'PUT',{decision:'approve',paymentVerified:true});
  const renewal=await (await request('/admin/subscription',owner,'admin',tenant,'POST',{...body,action:'renew',requestKey:randomUUID(),transactionReference:'TEST-RENEW-2'})).json();
  await request('/platform/billing/requests/'+renewal.id,platform,'platform_admin',null,'PUT',{decision:'approve',paymentVerified:true});
  check((await pool.query('SELECT current_period_end::text AS end FROM shops WHERE id=$1',[tenant])).rows[0].end>paidShop.current_period_end,'Early renewal adds paid time rather than replacing it');
  const switchBody={...body,planCode:'barberbook_plus',expectedAmount:1499,requestKey:randomUUID(),transactionReference:'TEST-PLUS-3'};
  const switchRequest=await (await request('/admin/subscription',owner,'admin',tenant,'POST',switchBody)).json();
  await request('/platform/billing/requests/'+switchRequest.id,platform,'platform_admin',null,'PUT',{decision:'reject',note:'The amount did not arrive.'});
  check((await pool.query('SELECT plan_code FROM shops WHERE id=$1',[tenant])).rows[0].plan_code==='barberbook','Rejected transfer leaves the current package unchanged');
  const correction=await (await request('/admin/subscription',owner,'admin',tenant,'POST',{...switchBody,requestKey:randomUUID()})).json();
  await request('/platform/billing/requests/'+correction.id,platform,'platform_admin',null,'PUT',{decision:'approve',paymentVerified:true});
  const ownerOnlyNotice=await request('/platform/notifications',platform,'platform_admin',null,'POST',{shopId:tenant,audience:'admin',title:'Owner update',body:'A private billing update for the owner.',path:'/admin?view=package'});
  const teamNotice=await request('/platform/notifications',platform,'platform_admin',null,'POST',{shopId:tenant,audience:'all',title:'Team update',body:'A helpful update for every workspace user.',path:'/admin'});
  const ownerFeed=await (await request('/auth/notifications',owner,'admin',tenant)).json();
  const deskFeed=await (await request('/auth/notifications',desk.id,'receptionist',tenant)).json();
  const ownerPrivateMessage=ownerFeed.notifications.find(message=>message.title==='Owner update');
  const ownerTeamMessage=ownerFeed.notifications.find(message=>message.title==='Team update');
  const deskTeamMessage=deskFeed.notifications.find(message=>message.title==='Team update');
  check(ownerOnlyNotice.status===200&&teamNotice.status===200&&ownerPrivateMessage&&!deskFeed.notifications.some(message=>message.title==='Owner update')&&ownerTeamMessage&&!ownerTeamMessage.readAt&&deskTeamMessage&&!deskTeamMessage.readAt,'Owner-only billing notes stay private while an operational message reaches the owner and front desk');
  await request('/auth/notifications/'+deskTeamMessage.id+'/read',desk.id,'receptionist',tenant,'PUT');
  const deskAfterRead=await (await request('/auth/notifications',desk.id,'receptionist',tenant)).json();
  const ownerAfterDeskRead=await (await request('/auth/notifications',owner,'admin',tenant)).json();
  const deskReadMessage=deskAfterRead.notifications.find(message=>message.id===deskTeamMessage.id);
  const ownerStillUnread=ownerAfterDeskRead.notifications.find(message=>message.id===ownerTeamMessage.id);
  check(!!deskReadMessage?.readAt&&ownerStillUnread?.readAt===null,'Reading a notification clears only that user’s counter and keeps the owner’s notice unread');
  const directory=await (await request('/platform/overview',platform,'platform_admin',null)).json();
  const subscriber=directory.shops.find(candidate=>candidate.id===tenant);
  check(subscriber?.owners.some(candidate=>candidate.email===signup.email&&candidate.phone==='+251912345688'),'Platform subscribers list each shop owner’s email and contact phone for direct Plus follow-up');
  check((await request('/platform/website-requests',platform,'platform_admin',null)).status===404&&(await request(`/platform/website-briefs/${tenant}`,platform,'platform_admin',null)).status===404,'Website briefs and publishing are no longer exposed in the platform workspace');
  const publicContact=await (await publicRequest('/public/platform-contact')).json();
  check(publicContact.email==='SaaSPlatform@test.local','The public footer can retrieve the configured platform contact');
  await request('/admin/shop/subscription',owner,'admin',tenant,'PUT',{action:'cancel'});
  check((await request('/admin/owner/report',owner,'admin',tenant)).status===402&&(await request('/admin/subscription',owner,'admin',tenant)).status===200,'Cancellation stops operations while preserving owner billing access');
  check((await publicRequest('/auth/login',{email:signup.email,password:signup.password})).status===200,'Cancelled owner can sign in to resubscribe');
  check((await publicRequest('/public/shop?shop=trialstudio')).status===404,'Cancelling a paid plan takes the shop website offline');
  const overview=await (await request('/platform/overview',platform,'platform_admin',null)).json();
  check(overview.shops.some(s=>s.id===tenant)&&overview.metrics.recurringRevenue===overview.shops.filter(s=>s.access.status==='active').reduce((sum,s)=>sum+Number(s.monthly_price),0),'Platform metrics exclude trials and inactive subscriptions from paid recurring revenue');
};
