import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { FiDownload, FiRefreshCw } from 'react-icons/fi';
import { useDeskResource, methodName, errorText } from '../Reception/desk';
import { type OwnerReport, cash, dayLabel, periodLabel } from './owner';
import { RevenueChart, BarberPerformance } from './OwnerCharts';
export default function OwnerFinancialReport(){
  const [params,setParams]=useSearchParams();
  const period=params.get('period')==='monthly'?'monthly':'weekly';
  const date=params.get('date')||'';
  const updateFilter=(key:string,value:string)=>setParams(current=>{const next=new URLSearchParams(current);if(value)next.set(key,value);else next.delete(key);return next;});
  const [exporting,setExporting]=useState(false),[exportError,setExportError]=useState('');
  const resource=useDeskResource<OwnerReport>(`/admin/owner/report?period=${period}${date?`&date=${encodeURIComponent(date)}`:''}`,60000);
  const r=resource.data;
  const download=async()=>{if(!r)return;setExporting(true);setExportError('');try{const {exportOwnerReport}=await import('../../utils/ownerReportPdf');exportOwnerReport(r);}catch(e){setExportError(errorText(e));}finally{setExporting(false);}};
  return <div className="owner-stack"><div className="owner-section-intro"><div><p>SHOP MONEY REPORT</p><h2>Your shop money</h2><span>Sales, payments, expenses, and stylist earnings for this time.</span></div><div className="owner-tools"><button className="admin-secondary-button" onClick={resource.refresh} aria-label="Refresh money report"><FiRefreshCw/></button><button className="admin-primary-button" disabled={!r||!!resource.error||exporting} onClick={download}><FiDownload/> {exporting?'Making PDF…':'Download PDF'}</button></div></div>
    {exportError&&<div className="admin-inline-error" role="alert">PDF could not be downloaded. {exportError}</div>}
    <div className="owner-filter-bar"><div className="desk-tabs" aria-label="Choose report time"><button aria-pressed={period==='weekly'} className={period==='weekly'?'is-active':''} onClick={()=>updateFilter('period','weekly')}>This week</button><button aria-pressed={period==='monthly'} className={period==='monthly'?'is-active':''} onClick={()=>updateFilter('period','monthly')}>This month</button></div><label>Choose a date in the {period==='weekly'?'week':'month'}<input className="admin-input" type="date" max={r?.shop.today} value={date||r?.shop.today||''} onChange={e=>updateFilter('date',e.target.value)}/></label></div>
    {resource.error&&<div className="admin-inline-error" role="alert">{resource.error}</div>}{resource.loading&&<p className="owner-loading">Loading money report…</p>}
    {r&&<><div className="owner-statement-title"><div><span>{r.shop.name}</span><h3>{period==='weekly'?'Weekly':'Monthly'} shop report</h3><p>{periodLabel(r)}{r.period.partial?' · So far':''}</p></div><small>Made {new Date(r.generatedAt).toLocaleString('en-GB')}</small></div>
    <div className="owner-two-col"><section className="owner-card"><div className="owner-card-head"><div><p>SALES AND EXPENSES</p><h3>Money summary</h3></div><span className="owner-unit">{r.shop.currency}</span></div><dl className="owner-statement"><div><dt>Service sales, without VAT</dt><dd>{cash(r.totals.sales,r.shop.currency)}</dd></div><div><dt>VAT collected</dt><dd>{cash(r.totals.vat,r.shop.currency)}</dd></div><div className="owner-subtotal"><dt>All customer payments</dt><dd>{cash(r.totals.collected,r.shop.currency)}</dd></div><div><dt>Shop expenses paid</dt><dd>− {cash(r.totals.expenses,r.shop.currency)}</dd></div><div className="owner-statement-total"><dt>Money left</dt><dd>{cash(r.totals.cashMovement,r.shop.currency)}</dd></div></dl><p className="owner-note">Money left means customer payments minus recorded expenses. It is not final profit because some costs may not be added yet.</p></section>
    <section className="owner-card"><div className="owner-card-head"><div><p>PERIOD TREND</p><h3>How the period unfolded</h3></div></div><div className="owner-legend"><span><i className="purple"/>Sales</span><span><i className="amber"/>Expenses</span></div><RevenueChart report={r}/></section></div>
    <section className="owner-card"><div className="owner-card-head"><div><p>MONEY IN AND OUT</p><h3>Money by account</h3></div></div><div className="owner-method-pills">{r.methods.map(m=><span key={m.method}>{methodName(m.method)} <b>{cash(m.collected,r.shop.currency)}</b></span>)}</div><div className="owner-table-scroll"><table className="owner-table"><thead><tr><th>Payment account</th><th>Method</th><th>Payments</th><th>Received</th><th>Expenses</th><th>Money left</th></tr></thead><tbody>{r.accounts.map((a,i)=><tr key={`${a.id}-${i}`}><td>{a.name}</td><td>{methodName(a.method)}</td><td>{a.count}</td><td>{cash(a.collected,r.shop.currency)}</td><td>{cash(a.expenses,r.shop.currency)}</td><td>{cash(a.collected-a.expenses,r.shop.currency)}</td></tr>)}</tbody></table></div>{!r.accounts.length&&<p className="owner-empty">No money was recorded in an account.</p>}<p className="owner-note">This shows payments saved in Mirror. It is not your full bank or Telebirr balance.</p></section>
    <div className="owner-equal-col"><section className="owner-card"><div className="owner-card-head"><div><p>SHOP SPENDING</p><h3>Expenses by type</h3></div></div><div className="owner-services">{r.categories.map(c=><div key={c.category}><span><strong>{c.category}</strong><small>{c.count} records</small></span><b>{cash(c.amount,r.shop.currency)}</b><div className="owner-bar-track"><span style={{width:`${r.totals.expenses?100*c.amount/r.totals.expenses:0}%`,background:'#d7a15d'}}/></div></div>)}</div>{!r.categories.length&&<p className="owner-empty">No expenses saved for this time.</p>}</section>
      <section className="owner-card"><div className="owner-card-head"><div><p>SALES BY STYLIST</p><h3>Team contribution</h3></div></div><BarberPerformance report={r}/></section></div>
    <section className="owner-card"><div className="owner-card-head"><div><p>STYLIST PAY</p><h3>Pay this period</h3></div></div><div className="owner-table-scroll"><table className="owner-table"><thead><tr><th>Stylist</th><th>How they are paid</th><th>Service sales</th><th>Percentage pay</th><th>Monthly salary</th></tr></thead><tbody>{r.barbers.map(b=><tr key={b.id}><td>{b.name}</td><td>{b.pay_mode==='hybrid'?'Salary + percentage':b.pay_mode==='commission'?'Percentage':'Salary only'}</td><td>{cash(b.sales,r.shop.currency)}</td><td>{cash(b.commission,r.shop.currency)}</td><td>{cash(b.monthly_salary,r.shop.currency)}</td></tr>)}</tbody></table></div><p className="owner-note">Percentage pay uses the rate saved when reception took payment. Monthly salary is the agreed amount. This page does not pay staff or add salary to expenses again.</p></section>
    <section className="owner-card"><div className="owner-card-head"><div><p>DAY CLOSING</p><h3>Closed days</h3></div></div><div className="owner-closing-list">{r.daily.map(d=>{const closing=r.closings.find(c=>c.day===d.day);const differences=closing?.differences.filter(v=>v.difference!==0)||[];return <article key={d.day}><div><strong>{dayLabel(d.day)}</strong><span>{closing?`Closed by ${closing.closedBy||'Reception'}`:d.collected||d.expenses||d.completed?'Day not closed':'No activity'}</span></div><b>{cash(d.collected,r.shop.currency)}</b><span className={`owner-badge ${differences.length?'amber':closing?'green':'neutral'}`}>{differences.length?'Check cash':closing?'Closed':'—'}</span>{differences.map(v=><p className="owner-warning" key={v.name}>{v.name}: counted {cash(v.counted,r.shop.currency)} · expected {cash(v.expected,r.shop.currency)} · difference {cash(v.difference,r.shop.currency)}</p>)}{closing?.notes&&<p>{closing.notes}</p>}</article>;})}</div></section>
    <details className="owner-card"><summary>Daily sales and expense list</summary><div className="owner-table-scroll"><table className="owner-table"><thead><tr><th>Day</th><th>Paid visits</th><th>Service sales</th><th>VAT</th><th>Collected</th><th>Expenses</th></tr></thead><tbody>{r.daily.map(d=><tr key={d.day}><td>{dayLabel(d.day)}</td><td>{d.customers}</td><td>{cash(d.sales,r.shop.currency)}</td><td>{cash(d.collected-d.sales,r.shop.currency)}</td><td>{cash(d.collected,r.shop.currency)}</td><td>{cash(d.expenses,r.shop.currency)}</td></tr>)}</tbody></table></div><div className="owner-table-scroll"><table className="owner-table"><thead><tr><th>Date</th><th>Category</th><th>Expense</th><th>Account</th><th>Recorded by</th><th>Amount</th></tr></thead><tbody>{r.expenses.map(e=><tr key={e.id}><td>{dayLabel(e.day)}</td><td>{e.category}</td><td>{e.description}</td><td>{e.account}</td><td>{e.recorded_by}</td><td>{cash(e.amount,r.shop.currency)}</td></tr>)}</tbody></table></div></details></>}
  </div>;
}
