import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { OwnerReport } from './owner';
import { cash, compact, dayLabel } from './owner';
import { methodName } from '../Reception/desk';
const colors=['#6254d9','#35a790','#f0b65d','#9a85e7','#e5869b'];
const chartStyle={borderRadius:14,border:'1px solid #e6e7ef',fontSize:14,boxShadow:'0 8px 28px #26344f12'};
export function RevenueChart({report:r}:{report:OwnerReport}){
  const days=r.chartDaily||r.daily;
  return <div className="owner-chart" role="img" aria-label={`Daily service sales and expenses in ${r.shop.currency}. Sales ${r.totals.sales}; expenses ${r.totals.expenses}.`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={days} margin={{top:12,right:12,left:-14,bottom:0}}><defs><linearGradient id="owner-sales-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7765e8" stopOpacity={.3}/><stop offset="95%" stopColor="#7765e8" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="4 6" vertical={false} stroke="#eceef4"/><XAxis dataKey="day" tickFormatter={d=>days.length<=7?dayLabel(d,true):d.slice(8)} axisLine={false} tickLine={false} tickMargin={12} minTickGap={20}/><YAxis tickFormatter={compact} axisLine={false} tickLine={false} width={60}/><Tooltip contentStyle={chartStyle} labelFormatter={d=>dayLabel(String(d))} formatter={(v,name)=>[cash(Number(v),r.shop.currency),name]}/><Area dot={days.length===1?{r:4}:false} name="Service sales" type="monotone" dataKey="sales" stroke="#6254d9" strokeWidth={3} fill="url(#owner-sales-fill)" isAnimationActive={false}/><Area dot={days.length===1?{r:4}:false} name="Expenses" type="monotone" dataKey="expenses" stroke="#d49645" strokeWidth={2} fill="none" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>;
}
export function CollectionChart({report:r}:{report:OwnerReport}){
  const rows=r.methods.filter(m=>m.collected>0);
  return <div className="owner-payment-chart"><div className="owner-donut" role="img" aria-label={`Collections ${cash(r.totals.collected,r.shop.currency)}`}>
    {rows.length?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={rows} dataKey="collected" nameKey="method" innerRadius="68%" outerRadius="95%" paddingAngle={3} stroke="none" isAnimationActive={false}>{rows.map((m,i)=><Cell key={m.method} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={chartStyle} formatter={(v,name)=>[cash(Number(v),r.shop.currency),methodName(String(name))]}/></PieChart></ResponsiveContainer>:<div className="owner-empty-ring"/>}<div className="owner-donut-label"><span>Collected</span><strong>{compact(r.totals.collected)}</strong><small>{r.shop.currency}</small></div></div>
    <div className="owner-chart-key">{rows.map((m,i)=><div key={m.method}><i style={{background:colors[i%colors.length]}}/><span>{methodName(m.method)}</span><strong>{cash(m.collected,r.shop.currency)}</strong></div>)}{!rows.length&&<p>No collections in this period.</p>}</div></div>;
}
export function VisitsChart({report:r}:{report:OwnerReport}){
  const days=r.chartDaily||r.daily;
  return <div className="owner-chart owner-chart-small" role="img" aria-label={`${r.totals.completed} completed visits, ${r.totals.cancelled} cancellations.`}><ResponsiveContainer width="100%" height="100%"><BarChart data={days} margin={{top:10,right:8,left:-25,bottom:0}}><CartesianGrid vertical={false} strokeDasharray="4 6" stroke="#eceef4"/><XAxis dataKey="day" tickFormatter={d=>days.length<=7?dayLabel(d,true):d.slice(8)} axisLine={false} tickLine={false} minTickGap={20}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip contentStyle={chartStyle} labelFormatter={d=>dayLabel(String(d))}/><Bar name="Completed visits" dataKey="completed" fill="#35a790" radius={[5,5,0,0]} maxBarSize={30} isAnimationActive={false}/><Bar name="Cancelled" dataKey="cancelled" fill="#ecc391" radius={[5,5,0,0]} maxBarSize={15} isAnimationActive={false}/></BarChart></ResponsiveContainer></div>;
}
export function TeamChart({report:r}:{report:OwnerReport}){
  const days=r.chartDaily||r.daily;
  return <div className="owner-chart owner-chart-small" role="img" aria-label="Number of stylists with completed visits each day"><ResponsiveContainer width="100%" height="100%"><BarChart data={days} margin={{top:10,right:8,left:-25,bottom:0}}><CartesianGrid vertical={false} strokeDasharray="4 6" stroke="#eceef4"/><XAxis dataKey="day" tickFormatter={d=>days.length<=7?dayLabel(d,true):d.slice(8)} axisLine={false} tickLine={false} minTickGap={20}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip contentStyle={chartStyle} labelFormatter={d=>dayLabel(String(d))}/><Bar name="Stylists serving" dataKey="working_barbers" fill="#9a85e7" radius={[5,5,0,0]} maxBarSize={28} isAnimationActive={false}/></BarChart></ResponsiveContainer></div>;
}
export function BarberPerformance({report:r}:{report:OwnerReport}){
  const max=Math.max(...r.barbers.map(b=>b.sales),1);
  return <div className="owner-performance">{r.barbers.map((b,i)=><div className="owner-barber-row" key={b.id}><span className="owner-initial" style={{background:colors[i%colors.length]+'18',color:colors[i%colors.length]}}>{b.name.slice(0,1)}</span><div><div className="owner-barber-label"><strong>{b.name}</strong><b>{cash(b.sales,r.shop.currency)}</b></div><div className="owner-bar-track"><span style={{width:`${100*b.sales/max}%`,background:colors[i%colors.length]}}/></div><small>{b.customers} paid visits · {b.active_days} days with completed visits</small></div></div>)}{!r.barbers.length&&<p className="owner-empty">Add your first stylist in Team to start tracking performance.</p>}</div>;
}
