import {useState} from 'react';
import {FiCheck,FiStar,FiRefreshCw,FiCreditCard,FiCopy} from 'react-icons/fi';
import api from '../../api/axios';
import {planContents} from '../../config/plans';
import {type SubscriptionDetails,type SubscriptionPlan,subscriptionDate} from '../../config/subscription';
import {useDeskResource,amount,errorText,methodName} from '../Reception/desk';
import DeskModal from '../Reception/DeskModal';
import '../../styles/owner.css';
export default function PackageManagement(){
  const resource=useDeskResource<SubscriptionDetails>('/admin/subscription');
  const [selected,setSelected]=useState<SubscriptionPlan|null>(null),[cancel,setCancel]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [accountId,setAccountId]=useState(''),[receipt,setReceipt]=useState<File|null>(null),[confirmed,setConfirmed]=useState(false),[requestKey,setRequestKey]=useState(''),[copied,setCopied]=useState(false);
  const data=resource.data, pending=data?.requests.find(r=>r.status==='pending'),account=data?.accounts.find(a=>String(a.id)===accountId);
  const choose=(plan:SubscriptionPlan)=>{setSelected(plan);setAccountId('');setReceipt(null);setConfirmed(false);setCopied(false);setError('');setRequestKey(crypto.randomUUID());};
  const copyDestination=async()=>{if(!account)return;try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(account.reference);else{const field=document.createElement('textarea');field.value=account.reference;field.setAttribute('readonly','');field.style.position='fixed';field.style.opacity='0';document.body.appendChild(field);field.select();if(!document.execCommand('copy'))throw new Error('copy failed');field.remove();}setCopied(true);window.setTimeout(()=>setCopied(false),1800);}catch{setError('Copy is unavailable here. Select the number and copy it manually.');}};
  const submit=async()=>{if(!selected||busy||!receipt)return;setBusy(true);setError('');try{const form=new FormData();form.append('action',selected.code===data?.shop.plan_code?'renew':'change');form.append('planCode',selected.code);form.append('accountId',String(Number(accountId)));form.append('paymentConfirmed',String(confirmed));form.append('requestKey',requestKey);form.append('expectedAmount',String(Number(selected.monthly_price)));form.append('receipt',receipt);await api.post('/admin/subscription',form,{headers:{'Content-Type':'multipart/form-data'}});setSelected(null);setNotice('Payment sent. Mirror will check the screenshot, then turn on your package.');await resource.refresh();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  const cancelSubscription=async()=>{setBusy(true);setError('');try{await api.put('/admin/shop/subscription',{action:'cancel'});setCancel(false);await resource.refresh();window.dispatchEvent(new Event('subscription-required'));}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  if(!data)return <div className="admin-inline-state">{resource.error||'Loading your package…'}{resource.error&&<button onClick={resource.refresh}>Try again</button>}</div>;
  const current=data.plans.find(p=>p.code===data.shop.plan_code);
  return <section className="admin-module-view desk-module">
    <header className="admin-module-header"><div><p className="admin-eyebrow">YOUR PACKAGE</p><h2 className="admin-module-title">Choose a package for your shop</h2><p className="admin-module-subtitle">Pay by bank or Telebirr. Mirror checks your payment screenshot, then turns on your package.</p></div><span className="admin-package-current"><FiStar/>{data.shop.plan_name}</span></header>
    {(resource.error||error)&&!selected&&!cancel&&<div className="admin-inline-error" role="alert">{error||resource.error}</div>}
    {notice&&<div className="desk-success" role="status"><FiCheck/>{notice}</div>}
    <section className="admin-module-card admin-subscription-controls"><div className="admin-module-toolbar"><div><p className="admin-card-kicker">{data.access.status.replaceAll('_',' ').toUpperCase()}</p><h3>{data.access.status==='trial'?`${data.access.daysRemaining} days left in your free trial`:data.shop.plan_name}</h3><p>{data.access.status==='trial'?`Trial ends ${subscriptionDate(data.access.trialEndsAt)}. Choose an available package to continue.`:data.access.periodEnd?`Current paid period ends ${subscriptionDate(data.access.periodEnd)}.`:'Choose a paid package when you are ready.'}</p></div></div>
      <div className="admin-subscription-actions">{current&&<button className="admin-primary-button" disabled={busy||!!pending||data.access.status==='suspended'} onClick={()=>choose(current)}><FiRefreshCw/>{data.access.status==='trial'?'Continue with '+current.name:'Renew package'}</button>}<button className="admin-secondary-button" disabled={busy||!!pending||['cancelled','suspended'].includes(data.access.status)} onClick={()=>{setCancel(true);setError('');}}>Cancel package</button></div>
      {pending&&<div className="desk-notice" role="status">We are checking your payment screenshot for {pending.plan_name}. Your current package works until it ends.</div>}
    </section>
    {!current&&<p className="desk-notice">Your old package is no longer offered. It works until it ends. Choose an available package for your next payment.</p>}
    <div className="admin-plan-grid">{data.plans.map(plan=><article className={`admin-plan-card ${plan.tier!=='basic'?'is-plus':''}`} key={plan.code}><div className="admin-plan-card-top"><span className="admin-plan-icon"><FiStar/></span>{data.shop.plan_code===plan.code&&<span className="admin-status-pill">Current package</span>}</div><h3>{plan.name}</h3><p>{plan.description}</p><strong>{amount(plan.monthly_price)}<small>/month</small></strong><ul>{planContents(plan).map((item,i)=><li key={i}><FiCheck/>{item}</li>)}</ul><button className="admin-primary-button" disabled={busy||!!pending||data.access.status==='suspended'} onClick={()=>choose(plan)}>{data.shop.plan_code===plan.code?'Renew':'Choose'} {plan.name}</button></article>)}</div>
    {!!data.requests.length&&<section className="admin-module-card"><h3>Package payments</h3><div className="saas-package-history">{data.requests.map(r=><article key={r.id}><div><strong>{r.plan_name} · {amount(r.amount,r.currency)}</strong><small>{subscriptionDate(r.requested_at)} · {r.payment_account_name}</small><small>{r.receipt_available?'Payment screenshot added':'Older request without a screenshot'}</small></div><span className={`admin-status-pill ${r.status==='approved'?'is-paid':'is-pending'}`}>{r.status}</span>{r.review_note&&<p>{r.review_note}</p>}</article>)}</div></section>}
    {selected&&<DeskModal title={`Choose ${selected.name}`} busy={busy} onClose={()=>setSelected(null)}><form className="desk-form" onSubmit={e=>{e.preventDefault();void submit();}}><div className="desk-visit-summary"><strong>{selected.name} · {amount(selected.monthly_price)} / month</strong><span>{selected.code===data.shop.plan_code?'Renewing adds one month to your current paid time.':'The new package starts for one month after Mirror checks your payment. Time left on the old package does not move to the new one.'}</span></div>{!data.accounts.length?<div className="desk-notice">Mirror has not added payment accounts yet. Come back before you send money.</div>:<><label className="admin-field">Send package payment to<select className="admin-input" required value={accountId} onChange={e=>{setAccountId(e.target.value);setConfirmed(false);setCopied(false);}}><option value="">Choose bank or Telebirr</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{methodName(a.method)} · {a.name}</option>)}</select></label>{account&&<div className="saas-payment-destination"><span>{account.name} · {methodName(account.method)}</span><div className="saas-payment-destination-copy"><strong>{account.reference}</strong><button type="button" className="admin-secondary-button" onClick={copyDestination}><FiCopy/>{copied?'Copied':'Copy number'}</button></div><span>Account holder: {account.account_holder}</span><strong>Send {amount(selected.monthly_price)}</strong></div>}<label className="admin-field">Payment screenshot<input className="admin-input" type="file" required accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0]||null;if(file&&file.size>5*1024*1024){setReceipt(null);setError('Screenshot must be 5 MB or smaller.');return;}setReceipt(file);setError('');setConfirmed(false);}}/>{receipt&&<small>{receipt.name} · {(receipt.size/1024).toFixed(0)} KB</small>}</label><label className="desk-checkbox"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I sent {amount(selected.monthly_price)} and attached the payment screenshot.</label><p className="desk-help">Attach a clear PNG, JPG, or WEBP screenshot. It must show the amount, date, and account that received it.</p></>}{error&&<div className="admin-inline-error" role="alert">{error}</div>}<button className="admin-primary-button" disabled={busy||!account||!receipt||!confirmed}><FiCreditCard/>{busy?'Sending…':'Send payment for checking'}</button></form></DeskModal>}
    {cancel&&<DeskModal title="Cancel your package?" busy={busy} onClose={()=>setCancel(false)}><div className="desk-form"><p className="desk-help">Cancelling turns off the shop pages now. Your records stay saved. You can sign in later, choose a package, and pay again. Old payments are not refunded.</p>{error&&<div className="admin-inline-error" role="alert">{error}</div>}<button className="admin-primary-button" disabled={busy} onClick={cancelSubscription}>{busy?'Cancelling…':'Confirm cancellation'}</button><button className="admin-secondary-button" disabled={busy} onClick={()=>setCancel(false)}>Keep my package</button></div></DeskModal>}
  </section>;
}
