import {useEffect,useMemo,useState} from 'react';
import {FiCheckCircle,FiDollarSign,FiSave} from 'react-icons/fi';
import api from '../../api/axios';
import {useDeskResource,amount,errorText,type FinanceSettings} from '../Reception/desk';
import {currentEthiopianDate,ethiopianLabel,ethiopianMonths} from '../../utils/ethiopianCalendar';

type Item={id:number;userId:number;employeeName:string;role:string;staffType:string|null;baseSalary:number;commission:number;adjustment:number;gross:number;payDay:number;payDueDate:string;note:string;paidAt:string|null;expenseId:number|null;paymentAccountName:string|null};
type PayrollData={run:null|{id:number;year:number;month:number;status:'draft'|'finalized';periodStart:string;periodEnd:string;finalized_at?:string};selection:{year:number;month:number;start:string;end:string};currency:string;items:Item[]};
type Draft={adjustment:string;note:string};
const initial=currentEthiopianDate();
const roleName=(item:Item)=>item.role==='barber'?'Stylist':item.role==='receptionist'?'Reception':item.staffType==='washer'?'Washer':item.staffType==='cleaner'?'Cleaner':'Support staff';

export default function Payroll(){
  const [year,setYear]=useState(initial.year),[month,setMonth]=useState(initial.month),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const resource=useDeskResource<PayrollData>(`/admin/payroll?year=${year}&month=${month}`,0);
  const finance=useDeskResource<FinanceSettings>('/admin/finance',0);
  const [drafts,setDrafts]=useState<Record<number,Draft>>({});
  const [paidFrom,setPaidFrom]=useState('');
  useEffect(()=>{if(resource.data)setDrafts(Object.fromEntries(resource.data.items.map(item=>[item.id,{adjustment:String(item.adjustment||''),note:item.note||''}])));},[resource.data]);
  const data=resource.data,total=useMemo(()=>data?.items.reduce((sum,item)=>sum+Number(item.gross||0),0)||0,[data]);
  const paidTotal=useMemo(()=>data?.items.filter(item=>!!item.paidAt).reduce((sum,item)=>sum+Number(item.gross||0),0)||0,[data]);
  const run=async(fn:()=>Promise<unknown>,success:string)=>{setBusy(true);setError('');setNotice('');try{await fn();setNotice(success);await resource.refresh();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  const saveItem=(item:Item)=>run(()=>api.put(`/admin/payroll/items/${item.id}`,drafts[item.id]||{adjustment:'0',note:''}),'Change saved.');
  if(!data)return <section className="admin-module-view desk-module"><div className={resource.error?'admin-inline-error':'owner-loading'}>{resource.error||'Loading monthly staff pay…'}</div></section>;
  const draft=data.run?.status==='draft';
  return <section className="admin-module-view desk-module">
    <header className="admin-module-header"><div><p className="admin-eyebrow">ETHIOPIAN CALENDAR PAY</p><h2 className="admin-module-title">Monthly staff pay</h2><p className="admin-module-subtitle">See monthly salary, percentage pay, and any changes for each staff member.</p></div></header>
    {(error||resource.error)&&<div className="admin-inline-error" role="alert">{error||resource.error}</div>}{notice&&<div className="desk-success" role="status"><FiCheckCircle/>{notice}</div>}
    <section className="admin-module-card"><div className="admin-module-toolbar"><div><p className="admin-card-kicker">PAY PERIOD</p><h3>{ethiopianLabel(year,month)}</h3><p className="desk-help">{data.selection.start} to {data.selection.end} in the Gregorian calendar.</p></div>{data.run?<span className={`admin-status-pill ${draft?'is-pending':'is-paid'}`}>{draft?'Pay list ready':'Pay list finished'}</span>:<button className="admin-primary-button" disabled={busy} onClick={()=>run(()=>api.post('/admin/payroll',{year,month}),'Monthly pay list is ready. It uses recorded salary and percentage pay.')}><FiDollarSign/> Prepare staff pay</button>}</div>
      <div className="admin-compensation-grid"><label className="admin-field">Ethiopian year<select className="admin-input" value={year} onChange={e=>setYear(Number(e.target.value))}>{Array.from({length:7},(_,i)=>initial.year-3+i).map(value=><option value={value} key={value}>{value}</option>)}</select></label><label className="admin-field">Ethiopian month<select className="admin-input" value={month} onChange={e=>setMonth(Number(e.target.value))}>{ethiopianMonths.map((name,index)=><option value={index+1} key={name}>{name}</option>)}</select></label></div>
      {!data.run&&<p className="desk-notice">Choose the Ethiopian month, then make the pay list. It uses each stylist’s pay rule and paid services for that month.</p>}
    </section>
    {data.run&&<><section className="admin-module-card"><div className="admin-module-toolbar"><div><p className="admin-card-kicker">TOTAL STAFF PAY</p><h3>{amount(total,data.currency)}</h3><p className="desk-help">{data.items.length} staff · {amount(paidTotal,data.currency)} already paid · Each pay date uses the person’s Ethiopian calendar day.</p></div>{draft&&<button className="admin-primary-button" disabled={busy} onClick={()=>run(()=>api.post(`/admin/payroll/${data.run!.id}/finalize`),'Pay list finished. After you pay someone, mark them paid.')}><FiCheckCircle/> Finish pay list</button>}</div>
      {!draft&&<div className="admin-payroll-payment-source"><label className="admin-field">Money used to pay salary<select className="admin-input" value={paidFrom} onChange={e=>setPaidFrom(e.target.value)}><option value="">Choose where the money came from</option>{(finance.data?.accounts||[]).filter(account=>account.active!==false).map(account=><option value={account.id} key={account.id}>{account.name} · {account.method==='cash'?'Cash':account.method==='telebirr'?'Telebirr':'Bank transfer'}</option>)}</select></label><p className="desk-help">When you mark a person paid, Mirror adds it to Expenses as <strong>Salary</strong>.</p></div>}
      <div className="admin-record-list">{data.items.map(item=>{const edit=drafts[item.id]||{adjustment:'',note:''};return <article className="admin-record-row" key={item.id}><div className="admin-record-main"><div className="admin-avatar admin-avatar-medium">{item.employeeName.slice(0,1)}</div><div><strong>{item.employeeName}</strong><span>{roleName(item)} · Due {item.payDueDate} · Ethiopian day {item.payDay}</span></div></div><div className="admin-payroll-amounts"><span>Salary <b>{amount(item.baseSalary,data.currency)}</b></span><span>Percentage pay <b>{amount(item.commission,data.currency)}</b></span><strong>{amount(item.gross,data.currency)}</strong></div>{draft?<div className="admin-payroll-edit"><input className="admin-input" aria-label={`Extra or less for ${item.employeeName}`} type="number" step="0.01" inputMode="decimal" value={edit.adjustment} placeholder="Extra or less" onChange={e=>setDrafts(current=>({...current,[item.id]:{...edit,adjustment:e.target.value}}))}/><input className="admin-input" aria-label={`Note for ${item.employeeName}`} maxLength={500} value={edit.note} placeholder="Note (optional)" onChange={e=>setDrafts(current=>({...current,[item.id]:{...edit,note:e.target.value}}))}/><button className="admin-secondary-button" disabled={busy} onClick={()=>saveItem(item)}><FiSave/> Save</button></div>:<div className="admin-payroll-edit"><span className={`admin-status-pill ${item.paidAt?'is-paid':'is-pending'}`}>{item.paidAt?'Paid':'Not paid yet'}</span>{item.paidAt&&<small className="desk-help">Salary expense{item.paymentAccountName?` · ${item.paymentAccountName}`:''}</small>}{!item.paidAt&&<button className="admin-secondary-button" disabled={busy||!paidFrom} title={!paidFrom?'Choose where the salary money came from first':''} onClick={()=>run(()=>api.post(`/admin/payroll/items/${item.id}/paid`,{accountId:Number(paidFrom)}),'Staff payment marked paid and added to Expenses as Salary.')}><FiCheckCircle/> Mark paid</button>}</div>}</article>;})}</div>{!data.items.length&&<p className="admin-empty-state">No staff to pay this month. Add stylists, reception, cleaners, or washers from Team.</p>}</section></>}
  </section>;
}
