import { useEffect, useRef, useState } from 'react';
import { FiCheckCircle, FiSend, FiSave } from 'react-icons/fi';
import api from '../../api/axios';
import { useDeskResource, errorText } from '../Reception/desk';
type Settings={configured:boolean;enabled:boolean;available:boolean;subscriptionStatus:string;chatId:string;telegramUsername?:string;history:Array<{id:number;day:string;status:string;attempts:number;error:string;sentAt:string;body:string}>};
export default function TelegramSettings(){
  const resource=useDeskResource<Settings>('/admin/owner/telegram',15000);
  const [form,setForm]=useState({botToken:'',telegramUsername:'',enabled:false});
  const initialized=useRef(false);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[verifiedUsername,setVerifiedUsername]=useState('');
  useEffect(()=>{if(resource.data&&!initialized.current){initialized.current=true;setForm(f=>({...f,telegramUsername:resource.data!.telegramUsername||'',enabled:resource.data!.enabled}));}},[resource.data]);
  const run=async(fn:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');setSuccess('');try{const result=await fn();setSuccess(typeof result==='string'?result:message);await resource.refresh();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  const available=!!resource.data?.available;
  return <div className="owner-stack desk-module"><div className="owner-section-intro"><div><p>STAY CLOSE TO YOUR SHOP</p><h2>Daily reports on Telegram</h2><span>One short message after closing: customer flow, income, expenses and low stock.</span></div><span className={`owner-badge ${resource.data?.enabled&&available?'green':'neutral'}`}><FiSend/>{resource.data?.enabled&&available?'Enabled':'Not enabled'}</span></div>
    {(error||resource.error)&&<div className="admin-inline-error" role="alert">{error||resource.error}</div>}{success&&<div className="desk-success" role="status"><FiCheckCircle/>{success}</div>}
    {resource.data&&!available&&<p className="desk-notice">Daily Telegram report is included during the 7-day trial and with Mirror Plus or Max. Your current package does not include it. Choose Plus or Max to restore this service.</p>}
    <div className="owner-two-col"><section className="owner-card"><p className="owner-eyebrow">SET UP ONCE</p><h3>Connect the owner’s Telegram</h3><ol className="telegram-setup-steps"><li><span>1</span><div><strong>Create a bot</strong><p>Open <a href="https://t.me/BotFather" target="_blank" rel="noreferrer">@BotFather</a> in Telegram, send <code>/newbot</code>, and copy the bot token it gives you.</p></div></li><li><span>2</span><div><strong>Start your bot</strong><p>Search for the new bot from the Telegram account that should receive the reports, open it, and tap <b>Start</b>.</p></div></li><li><span>3</span><div><strong>Save this connection</strong><p>Paste the token, enter that account’s <b>@username</b>, tick daily digest, and save.</p></div></li><li><span>4</span><div><strong>Verify it</strong><p>Select <b>Verify saved connection</b>. After the green confirmation, daily reports will reach that username after closing.</p></div></li></ol>
      <form className="desk-form" onSubmit={e=>{e.preventDefault();setVerifiedUsername('');run(async()=>{await api.put('/admin/owner/telegram',form);setForm(f=>({...f,botToken:''}));},form.enabled?'Telegram settings saved. Reports are sent after the next daily closing.':'Telegram settings saved. Daily delivery is disabled.');}}>
        <fieldset className="owner-form-fields" disabled={busy||resource.loading||!resource.data||!available}>
        <label className="admin-field">Bot token<input className="admin-input" autoComplete="new-password" type="password" value={form.botToken} placeholder={resource.data?.configured?'Saved securely · leave blank to keep':'Paste the token from BotFather'} onChange={e=>setForm({...form,botToken:e.target.value})} required={!resource.data?.configured}/></label>
        <label className="admin-field">Owner Telegram username<input className="admin-input" value={form.telegramUsername} pattern="@?[A-Za-z0-9_]{5,32}" title="Enter the Telegram username, for example @yourname." placeholder="@yourname" required onChange={e=>{setVerifiedUsername('');setForm({...form,telegramUsername:e.target.value});}}/></label>
        <label className="desk-checkbox"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Send the daily closing digest to this Telegram chat.</label>
        <div className="owner-tools"><button disabled={busy||resource.loading} className="admin-primary-button"><FiSave/>{busy?'Please wait…':'Save connection'}</button><button type="button" disabled={busy||!resource.data?.configured} className="admin-secondary-button" onClick={()=>run(async()=>{const {data}=await api.post('/admin/owner/telegram/verify');setVerifiedUsername(form.telegramUsername.startsWith('@')?form.telegramUsername:`@${form.telegramUsername}`);return `Saved connection verified: @${data.bot} → ${data.chat}.`;},'Saved connection verified.')}>Verify saved connection</button></div>
        </fieldset>
      </form>{verifiedUsername&&<div className="desk-payment-success telegram-verification-success" role="status"><svg className="desk-success-tick" viewBox="0 0 72 72" aria-hidden="true"><circle className="desk-tick-circle" cx="36" cy="36" r="31"/><path className="desk-tick-check" d="M21 36l10 10 21-23"/></svg><div><h3>Telegram connected</h3><p>Daily reports will be sent to <strong>{verifiedUsername}</strong> after reception closes the day.</p></div></div>}<p className="owner-note">Included in the free trial and with Plus or Max. Mirror and this computer need internet to send reports. If a closing is corrected, the same day’s message is updated. Package decisions and notes are in <b>Platform messages</b> on this page.</p>
    </section><section className="owner-card owner-digest-preview"><p className="owner-eyebrow">THE DAILY DIGEST</p><h3>Your day in four lines</h3><ol><li><strong>Customer flow</strong><span>Customers served, plus cancellations if any.</span></li><li><strong>Daily income</strong><span>Total service sales for the day, excluding VAT.</span></li><li><strong>Daily expenses</strong><span>Total recorded shop expenses for the day.</span></li><li><strong>Low stock alert</strong><span>A short list of supplies running low and their remaining quantities.</span></li></ol></section></div>
    <section className="owner-card"><div className="owner-card-head"><div><p>DELIVERY HISTORY</p><h3>Every closing, accounted for</h3></div></div><div className="owner-deliveries">{resource.data?.history.map(h=><article key={h.id}><div><strong>{h.day}</strong><span className={`owner-badge ${h.status==='sent'?'green':h.status==='failed'||h.status==='uncertain'?'amber':'neutral'}`}>{({queued:'Queued for delivery',sending:'Sending',sent:'Delivered',failed:'Failed',uncertain:'Check Telegram',skipped:'Not included in package'} as Record<string,string>)[h.status]}</span></div>{h.error&&<p className="owner-warning">{h.error}</p>}{h.status==='failed'&&<button className="admin-secondary-button" disabled={busy} onClick={()=>run(()=>api.post(`/admin/owner/telegram/${h.id}/retry`),'Delivery queued again.')}>Retry delivery</button>}<details><summary>View the saved digest</summary><pre>{h.body}</pre></details></article>)}</div>{resource.data&&!resource.data.history.length&&<p className="owner-empty">When connected, the next daily closing will appear here.</p>}</section>
  </div>;
}
