import {useState} from 'react';
import {FiCheckCircle,FiSend} from 'react-icons/fi';
import api from '../../api/axios';
import {useDeskResource,errorText} from '../../Components/Reception/desk';

type Shop={id:number;name:string};
type History={id:number;shopId:number;shopName:string;title:string;body:string;path:string;audience:'admin'|'staff'|'all';createdAt:string;readAt:string|null};
export default function PlatformMessages(){
  const shops=useDeskResource<{shops:Shop[]}>('/platform/overview',0);
  const history=useDeskResource<{history:History[]}>('/platform/notifications',12000);
  const [form,setForm]=useState({shopId:'all',audience:'admin',title:'',body:'',path:'/admin'}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const send=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');setNotice('');try{const {data}=await api.post<{sent:number}>('/platform/notifications',form);setForm({shopId:'all',audience:'admin',title:'',body:'',path:'/admin'});setNotice(`Message sent to ${data.sent} shop${data.sent===1?'':'s'}.`);await history.refresh();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  return <section className="desk-module"><header className="admin-module-header"><div><p className="admin-eyebrow">SEND A MESSAGE</p><h2 className="admin-module-title">Message shops</h2><p className="admin-module-subtitle">Send a message to owners, staff, or everyone in a shop.</p></div></header>
    {(error||history.error)&&<div className="admin-inline-error" role="alert">{error||history.error}</div>}{notice&&<div className="desk-success" role="status"><FiCheckCircle/>{notice}</div>}
    <form className="admin-module-card desk-form" onSubmit={send}><div className="admin-compensation-grid"><label className="admin-field">Send to<select className="admin-input" value={form.shopId} onChange={e=>setForm({...form,shopId:e.target.value})}><option value="all">Every shop</option>{shops.data?.shops.map(shop=><option value={shop.id} key={shop.id}>{shop.name}</option>)}</select></label><label className="admin-field">Who sees it<select className="admin-input" value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}><option value="admin">Shop owner only</option><option value="all">All owners and staff</option><option value="staff">Staff only</option></select><small>Use owner only for package or payment messages. Other messages show in the bell.</small></label><label className="admin-field">Open this page<select className="admin-input" value={form.path} onChange={e=>setForm({...form,path:e.target.value})}><option value="/admin">Owner page</option><option value="/admin?view=package">Package and payment</option><option value="/admin?view=team">Staff</option></select></label></div><label className="admin-field">Message title<input className="admin-input" required maxLength={160} placeholder="e.g. Important update" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="admin-field">Message<textarea className="admin-input" required maxLength={1000} placeholder="Write a short and clear message." value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><button className="admin-primary-button" disabled={busy}><FiSend/>{busy?'Sending…':'Send message'}</button></form>
    <section className="admin-module-card"><div className="admin-module-toolbar"><div><p className="admin-card-kicker">MESSAGES SENT</p><h3>Recent platform messages</h3></div></div><div className="saas-package-history">{history.data?.history.map(message=><article key={message.id}><div><strong>{message.shopName} · {message.title}</strong><small>{new Date(message.createdAt).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})} · {message.audience==='admin'?'Owner only':message.audience==='staff'?'Staff only':'Everyone'}</small><p>{message.body}</p></div><span className={`admin-status-pill ${message.readAt?'is-paid':'is-pending'}`}>{message.readAt?'Read':'Not read'}</span></article>)}</div>{!history.loading&&!history.data?.history.length&&<p className="admin-empty-state">Messages you send will appear here.</p>}</section>
  </section>;
}
