import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {FiArrowRight,FiCheckCircle,FiSave,FiSend} from 'react-icons/fi';
import api from '../../api/axios';
import {useDeskResource,errorText,dateTime} from '../../Components/Reception/desk';
type Settings={configured:boolean;enabled:boolean;chatId:string;telegramUsername?:string;workspaceUrl:string;history:Array<{id:number;title:string;body:string;kind:string;path:string;status:string;error:string;created_at:string}>};
const delivery:Record<string,string>={sent:'Delivered',queued:'Queued',sending:'Sending',failed:'Failed',uncertain:'Check Telegram',skipped:'Alerts were off'};
export default function PlatformTelegram(){
  const resource=useDeskResource<Settings>('/platform/telegram',15000),initialized=useRef(false);
  const [form,setForm]=useState({botToken:'',telegramUsername:'',enabled:false,workspaceUrl:window.location.origin}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[filter,setFilter]=useState('all');
  useEffect(()=>{if(resource.data&&!initialized.current){initialized.current=true;setForm(f=>({...f,telegramUsername:resource.data!.telegramUsername||resource.data!.chatId||'',enabled:resource.data!.enabled,workspaceUrl:resource.data!.workspaceUrl||window.location.origin}));}},[resource.data]);
  const run=async(fn:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');setSuccess('');try{const result=await fn();setSuccess(typeof result==='string'?result:message);await resource.refresh();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  const local=/^https?:\/\/(localhost|127\.0\.0\.1|\[::1\])(:|\/|$)/i.test(form.workspaceUrl);
  return <div className="owner-stack desk-module"><header className="admin-module-header"><div><p className="admin-eyebrow">TELEGRAM UPDATES</p><h2 className="admin-module-title">Important updates on Telegram</h2><p className="admin-module-subtitle">Short messages for new trials, payment requests, cancelled packages, and packages that ended.</p></div><span className={'owner-badge '+(resource.data?.enabled?'green':'neutral')}><FiSend/>{resource.data?.enabled?'Updates on':'Not connected'}</span></header>
    {(resource.error||error)&&<p className="admin-inline-error" role="alert">{error||resource.error}</p>}{success&&<p className="desk-success" role="status"><FiCheckCircle/>{success}</p>}
    <div className="owner-two-col"><section className="owner-card"><h3>Platform admin connection</h3><p className="owner-note">This is the one-time technical setup. Create a bot with <a href="https://t.me/BotFather" target="_blank" rel="noreferrer">@BotFather</a>, then enter the bot token and the platform admin username below. Shop owners only enter their own Telegram username.</p><form className="desk-form" onSubmit={e=>{e.preventDefault();run(async()=>{await api.put('/platform/telegram',form);setForm(f=>({...f,botToken:''}));},form.enabled?'Connection saved. Future platform activity will send alerts.':'Connection saved. Telegram alerts are off.');}}><fieldset className="owner-form-fields" disabled={busy||resource.loading||!resource.data}>
      <label className="admin-field">Bot token<input className="admin-input" type="password" autoComplete="new-password" required={!resource.data?.configured} value={form.botToken} placeholder={resource.data?.configured?'Saved securely · leave blank to keep':'Token from BotFather'} onChange={e=>setForm({...form,botToken:e.target.value})}/></label>
      <label className="admin-field">Platform admin Telegram username<input className="admin-input" required pattern="(?:@?[A-Za-z0-9_]{5,32}|-?[0-9]{1,20})" title="Enter a Telegram username, for example @yourname." placeholder="@yourname" value={form.telegramUsername} onChange={e=>setForm({...form,telegramUsername:e.target.value})}/></label>
      <label className="admin-field">Mirror website address<small>Used for links that open the right payment or shop.</small><input className="admin-input" type="url" required value={form.workspaceUrl} onChange={e=>setForm({...form,workspaceUrl:e.target.value})}/></label>
      {local&&<p className="desk-notice">This is a local address. Telegram links work only on this computer while Mirror is running.</p>}
      <label className="desk-checkbox"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Send future platform updates to this chat.</label>
      <div className="platform-card-actions"><button className="admin-primary-button" disabled={busy}><FiSave/>{busy?'Please wait…':'Save connection'}</button><button className="admin-secondary-button" type="button" disabled={busy||!resource.data?.configured} onClick={()=>run(async()=>{const {data}=await api.post('/platform/telegram/verify');return 'Saved connection verified: @'+data.bot+' → '+data.chat+'.';},'Connection verified.')}>Verify saved connection</button></div>
      </fieldset></form><p className="owner-note">The token is saved safely. Mirror and this computer need internet for messages to send. Old activity stays in the list and is not sent when you turn on updates.</p></section>
      <section className="owner-card"><p className="owner-eyebrow">WHAT A MESSAGE LOOKS LIKE</p><h3>A few lines. One clear action.</h3><pre className="platform-telegram-preview">{'Payment needs checking\nExample Salon\nShop owner · owner@example.com\nMirror Plus · ETB 1,499\nPlatform bank\n\nOpen page: [payment link]'}</pre><p className="owner-note">Example only. The link opens the payment after the platform admin signs in.</p><ul className="platform-core-details"><li>New shop and 7-day trial started</li><li>Payment sent for checking</li><li>Payment approved or rejected</li><li>Owner cancelled a package</li><li>Trial or paid package ended</li></ul></section></div>
    <section className="owner-card"><div className="owner-card-head"><div><p>RECENT PLATFORM ACTIVITY</p><h3>Keep every update in view</h3></div><label className="admin-field">Activity<select className="admin-input" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All activity</option><option value="signup">New trials</option><option value="payment_requested">Payment requests</option><option value="payment_reviewed">Payment decisions</option><option value="cancelled">Cancellations</option><option value="expiry">Expiries</option><option value="problems">Delivery problems</option></select></label></div>
      <div className="platform-activity">{resource.data?.history.filter(e=>filter==='all'||e.kind===filter||filter==='problems'&&['failed','uncertain'].includes(e.status)).map(e=><article key={e.id}><div className="platform-activity-head"><strong>{e.title}</strong><span className={'owner-badge '+(e.status==='sent'?'green':['failed','uncertain'].includes(e.status)?'amber':'neutral')}>{delivery[e.status]}</span></div><time>{dateTime(e.created_at)}</time><pre>{e.body}</pre>{e.error&&<p className="owner-warning">{e.error}</p>}<div className="platform-card-actions"><Link to={e.path}>Open page <FiArrowRight/></Link>{e.status==='failed'&&<button className="admin-secondary-button" disabled={busy||!resource.data?.enabled} onClick={()=>run(()=>api.post('/platform/telegram/'+e.id+'/retry'),'Message will try again.')}>Try again</button>}</div></article>)}</div>{resource.data&&!resource.data.history.length&&<p className="owner-empty">New platform updates will appear here, even before you connect Telegram.</p>}<p className="owner-note">Showing the latest 60 updates. Messages that may not have sent are held here so they do not send twice.</p>
    </section>
  </div>;
}
