import {useState} from 'react';
import {FiCheck,FiEdit2,FiPlus,FiTrash2} from 'react-icons/fi';
import api from '../../api/axios';
import {useDeskResource,amount,errorText} from '../../Components/Reception/desk';
import DeskModal from '../../Components/Reception/DeskModal';
import {coreContents,planContents} from '../../config/plans';
import type {SubscriptionPlan} from '../../config/subscription';
const blank:SubscriptionPlan={code:'',name:'',description:'',monthly_price:799,tier:'basic',highlights:[],features:{publicWebsite:false,onlineBooking:false,inventoryAlerts:false},limits:{staff:5,dailyCustomers:20}};
export default function PlatformPackages({onChange}:{onChange:()=>void}){
  const resource=useDeskResource<SubscriptionPlan[]>('/platform/packages');
  const [form,setForm]=useState<SubscriptionPlan|null>(null),[editing,setEditing]=useState(false),[contents,setContents]=useState(''),[remove,setRemove]=useState<SubscriptionPlan|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
  const open=(p?:SubscriptionPlan)=>{setEditing(!!p);setForm(p?{...p,features:{publicWebsite:p.tier==='max'&&!!p.features.publicWebsite,onlineBooking:p.tier==='max'&&!!p.features.onlineBooking,inventoryAlerts:!!p.features.inventoryAlerts}}:{...blank});setContents((p?.highlights||[]).join('\n'));setError('');};
  const run=async(fn:()=>Promise<unknown>,message:string)=>{if(busy)return;setBusy(true);setError('');try{await fn();setForm(null);setRemove(null);setSuccess(message);await resource.refresh();onChange();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  return <div className="owner-stack desk-module"><header className="admin-module-header"><div><p className="admin-eyebrow">MIRROR PACKAGES</p><h2 className="admin-module-title">Packages for shops</h2><p className="admin-module-subtitle">Add, change, or remove the packages owners can choose.</p></div><button className="admin-primary-button" onClick={()=>open()}><FiPlus/> Add package</button></header>
    {(error||resource.error)&&!form&&!remove&&<p className="admin-inline-error" role="alert">{error||resource.error}</p>}{success&&<p className="desk-success" role="status"><FiCheck/>{success}</p>}
    <p className="desk-notice">Changes update the price and what the package includes. Shops keep their current package. Old payment requests keep their original amount.</p>
    <div className="platform-package-grid">{resource.data?.map(p=><article className={'owner-card platform-package '+(!p.active?'is-removed':'')} key={p.code}><div className="platform-card-heading"><span className={'owner-badge '+(p.active?'green':'neutral')}>{p.active?'Available':'Removed from sale'}</span>{p.is_trial_default&&<span className="owner-badge">7-day trial package</span>}</div><h3>{p.name}</h3><p>{p.description}</p><strong className="platform-price">{amount(p.monthly_price)}<small> / month</small></strong><ul>{planContents(p).map((item,i)=><li key={i}><FiCheck/>{item}</li>)}</ul><p className="owner-note">{p.shop_count||0} shops currently assigned · {p.tier[0].toUpperCase()+p.tier.slice(1)} package</p><div className="platform-card-actions"><button className="admin-secondary-button" onClick={()=>open(p)} disabled={busy}><FiEdit2/> Edit</button>{p.active?<button className="admin-secondary-button" disabled={busy} onClick={()=>{setRemove(p);setError('');}}><FiTrash2/> Remove</button>:<button className="admin-secondary-button" disabled={busy} onClick={()=>run(()=>api.post('/platform/packages/'+p.code+'/restore'),'Package restored to sale.')}>Restore</button>}{p.active&&!p.is_trial_default&&<button className="admin-secondary-button" disabled={busy} onClick={()=>run(()=>api.post('/platform/packages/'+p.code+'/trial'),'New trials will use this package. Existing shops keep their package.')}>Use for new trials</button>}</div></article>)}</div>{resource.loading&&<p>Loading packages…</p>}
    {form&&<DeskModal title={editing?'Edit '+form.name:'Create a package'} busy={busy} onClose={()=>setForm(null)}><form className="desk-form" onSubmit={e=>{e.preventDefault();const data={...form,highlights:contents.split('\n').map(v=>v.trim()).filter(Boolean)};run(()=>editing?api.put('/platform/packages/'+form.code,data):api.post('/platform/packages',data),'Package saved. Pricing and checkout now show the updated offer.');}}>
      <label className="admin-field">Package name<input className="admin-input" value={form.name} required maxLength={80} onChange={e=>setForm({...form,name:e.target.value})}/></label>
      {!editing&&<label className="admin-field">Package code<small>A unique reference, such as mirror_team.</small><input className="admin-input" value={form.code} required pattern="[a-z][a-z0-9_]{2,39}" maxLength={40} onChange={e=>setForm({...form,code:e.target.value.toLowerCase()})}/></label>}
      <label className="admin-field">Description<textarea className="admin-input" value={form.description} required maxLength={400} onChange={e=>setForm({...form,description:e.target.value})}/></label>
      <div className="platform-form-pair"><label className="admin-field">Monthly price · ETB<input className="admin-input" type="number" required min="0.01" max="99999999.99" step="0.01" value={form.monthly_price} onChange={e=>setForm({...form,monthly_price:e.target.value})}/></label><label className="admin-field">Staff accounts<input className="admin-input" type="number" required min={3} max={1000} value={form.limits.staff||3} onChange={e=>setForm({...form,limits:{...form.limits,staff:Number(e.target.value)}})}/></label></div>
      <label className="admin-field">Package level<select className="admin-input" value={form.tier} onChange={e=>{const tier=e.target.value as 'basic'|'plus'|'max';setForm({...form,tier,features:{...form.features,...(tier!=='max'?{publicWebsite:false,onlineBooking:false}:{})}});}}><option value="basic">Basic · 20 customers each day</option><option value="plus">Plus · 50 customers each day</option><option value="max">Max · unlimited customers</option></select></label>
      <fieldset className="platform-feature-fields"><legend>What the package includes</legend><label className="desk-checkbox"><input type="checkbox" disabled={form.tier!=='max'} checked={!!form.features.publicWebsite} onChange={e=>setForm({...form,features:{...form.features,publicWebsite:e.target.checked,...(!e.target.checked?{onlineBooking:false}:{})}})}/> Website support <small>Mirror Max only</small></label><label className="desk-checkbox"><input type="checkbox" disabled={form.tier!=='max'||!form.features.publicWebsite} checked={!!form.features.onlineBooking} onChange={e=>setForm({...form,features:{...form.features,onlineBooking:e.target.checked}})}/> Online booking support <small>Mirror Max only</small></label><p className="desk-help">Daily customers are fixed: Basic 20, Plus 50, Max unlimited. Daily Telegram reports are in Plus and Max only. Website and online booking are in Max only. One package is for one shop.</p></fieldset>
      <label className="admin-field">Additional package contents<small>One benefit per line, up to 12. These appear on pricing and checkout.</small><textarea className="admin-input" rows={5} value={contents} onChange={e=>setContents(e.target.value)}/></label>
      <details className="platform-core-details"><summary>Included in every package</summary><ul>{coreContents.map(c=><li key={c}>{c}</li>)}</ul><p className="desk-help">Every package includes these main tools. The check boxes above turn optional features on or off.</p></details>
      {editing&&<p className="desk-help">Current shops retain this package. Capability and team-limit edits apply to it; existing team accounts are preserved. Removed packages can be restored from the catalog.</p>}
      {error&&<p className="admin-inline-error" role="alert">{error}</p>}<button className="admin-primary-button" disabled={busy}>{busy?'Saving…':'Save package'}</button>
    </form></DeskModal>}
    {remove&&<DeskModal title={'Remove '+remove.name+'?'} busy={busy} onClose={()=>setRemove(null)}><div className="desk-form"><p>It will disappear from public pricing and future purchases. Existing subscriptions and submitted payments stay valid. You can restore the package later.</p>{remove.is_trial_default&&<p className="desk-notice">Choose another package for new trials first, then remove this package.</p>}{error&&<p className="admin-inline-error" role="alert">{error}</p>}<button className="admin-primary-button" disabled={busy||remove.is_trial_default} onClick={()=>run(()=>api.delete('/platform/packages/'+remove.code),'Package removed from sale. Existing subscriptions are preserved.')}>{busy?'Removing…':'Remove from sale'}</button></div></DeskModal>}
  </div>;
}
