import {useState} from 'react';
import {FiArrowRight,FiCheckCircle,FiClock,FiCreditCard,FiGrid,FiLogOut,FiMenu,FiRefreshCw,FiSend,FiStar,FiUsers,FiX,FiSearch,FiMessageCircle,FiUser} from 'react-icons/fi';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {useAppDispatch,useAppSelector} from '../../app/hooks';
import {logoutUser} from '../../features/auth/authThunks';
import {useDeskResource,amount} from '../../Components/Reception/desk';
import api from '../../api/axios';
import DeskModal from '../../Components/Reception/DeskModal';
import {subscriptionDate,type SubscriptionPlan} from '../../config/subscription';
import PlatformBilling from './PlatformBilling';
import PlatformPackages from './PlatformPackages';
import PlatformTelegram from './PlatformTelegram';
import PlatformMessages from './PlatformMessages';
import ProfileSettings from '../../Components/ProfileSettings';
import NotificationsBell from '../../Components/NotificationsBell';
import '../../styles/owner.css';
import '../../styles/platform.css';

type View='overview'|'shops'|'packages'|'billing'|'messages'|'telegram'|'profile';
const navigation=[{id:'overview',label:'Overview',icon:FiGrid},{id:'shops',label:'Shops',icon:FiUsers},{id:'billing',label:'Payments',icon:FiCreditCard},{id:'packages',label:'Packages',icon:FiStar},{id:'messages',label:'Messages',icon:FiMessageCircle},{id:'telegram',label:'Telegram updates',icon:FiSend},{id:'profile',label:'My profile',icon:FiUser}] as const;
const statusNames:Record<string,string>={trial:'Free trial',active:'Paid · active',cancelled:'Cancelled',trial_expired:'Trial ended',past_due:'Payment ended',suspended:'Paused'};
type Shop={id:number;name:string;slug:string;plan_code:string;plan_name:string;plan_available:boolean;subscription_source:'trial'|'paid'|'free_grant';staff_count:number;created_at:string;trial_ends_at:string;cancelled_at:string|null;onboarding_completed_at:string|null;owners:Array<{name:string;email:string;phone:string|null}>;pending_payment:null|{id:number;plan_name:string;amount:number};last_payment:null|{plan_name:string;amount:number};access:{status:string;daysRemaining:number;periodEnd:string|null}};
type Data={shops:Shop[];plans:SubscriptionPlan[];metrics:{shops:number;active:number;trial:number;cancelled:number;expired:number;pending:number;recurringRevenue:number}};
const Badge=({status,source}:{status:string;source?:Shop['subscription_source']})=><span className={'platform-status status-'+status}>{status==='active'&&source==='free_grant'?'Free · active':statusNames[status]||status}</span>;

export default function PlatformDashboard(){
  const dispatch=useAppDispatch(),navigate=useNavigate(),user=useAppSelector(s=>s.auth.user);
  const [params,setParams]=useSearchParams(),[sidebar,setSidebar]=useState(false),[grantShop,setGrantShop]=useState<Shop|null>(null),[grantMessage,setGrantMessage]=useState('');
  const view=(navigation.some(n=>n.id===params.get('view'))?params.get('view'):'overview') as View;
  const resource=useDeskResource<Data>('/platform/overview'),data=resource.data;
  const go=(next:View,extra:Record<string,string>={})=>{setParams({view:next,...extra});setSidebar(false);window.scrollTo({top:0,behavior:'smooth'});};
  const signOut=async()=>{await dispatch(logoutUser());navigate('/login');};
  const alerts=<NotificationsBell feedPath="/platform/alerts" readPath="/platform/alerts" emptyMessage="New shops, payment requests, and other updates show here."/>;
  return <div className="platform-workspace"><header className="platform-mobile-header"><button className="admin-icon-button" aria-label="Open platform menu" onClick={()=>setSidebar(true)}><FiMenu/></button><div className="platform-brand"><img src="/mirror.svg" alt=""/>Mirror</div><div className="platform-mobile-actions">{alerts}<button className="admin-icon-button" aria-label="Refresh shops" onClick={resource.refresh}><FiRefreshCw/></button></div></header>
    {sidebar&&<button className="platform-sidebar-backdrop" aria-label="Close platform menu" onClick={()=>setSidebar(false)}/>}
    <aside className={'platform-sidebar '+(sidebar?'is-open':'')}><div className="platform-sidebar-top"><div className="platform-brand"><img src="/mirror.svg" alt=""/>Mirror</div><button className="admin-icon-button platform-sidebar-close" aria-label="Close platform menu" onClick={()=>setSidebar(false)}><FiX/></button></div><div className="platform-label"><span>PLATFORM ADMIN</span><strong>All Mirror shops</strong></div><nav className="platform-nav" aria-label="Platform menu">{navigation.map(n=><button className={view===n.id?'is-active':''} aria-current={view===n.id?'page':undefined} key={n.id} onClick={()=>go(n.id)}><n.icon/><span>{n.label}</span>{n.id==='billing'&&!!data?.metrics.pending&&<b>{data.metrics.pending}</b>}</button>)}</nav><div className="platform-sidebar-footer"><div className="platform-user"><span>{user?.name?.slice(0,1)||'P'}</span><div><strong>{user?.name||'Platform admin'}</strong><small>Mirror platform</small></div></div><button onClick={signOut}><FiLogOut/> Sign out</button></div></aside>
    <main className="platform-main"><header className="platform-topbar"><div><p className="admin-eyebrow">MIRROR PLATFORM</p><h1>{view==='overview'?'Your platform today':navigation.find(n=>n.id===view)?.label}</h1><p className="platform-subtitle">{view==='overview'?'See new shops, payments, and shops that need help.':'One place to support all Mirror shops.'}</p></div><div className="platform-topbar-actions">{alerts}</div></header>
      {resource.error&&<p className="admin-inline-error" role="alert">{resource.error} <button onClick={resource.refresh}>Try again</button></p>}{grantMessage&&<div className="desk-success" role="status"><FiCheckCircle/>{grantMessage}</div>}
      {(view==='overview'||view==='shops')&&!data&&<p className="owner-card">Loading shops…</p>}
      {view==='overview'&&data&&<div className="owner-stack">
        <div className="platform-kpis">{[{label:'All shops',value:data.metrics.shops,icon:FiUsers,filter:'all',note:'Every shop using Mirror'},{label:'Free trials',value:data.metrics.trial,icon:FiClock,filter:'trial',note:'Using the 7 free days'},{label:'Paid shops',value:data.metrics.active,icon:FiStar,filter:'active',note:'Using a paid package'},{label:'Cancelled',value:data.metrics.cancelled,icon:FiX,filter:'cancelled',note:'Shops that stopped'}].map(k=><button className="owner-card platform-kpi" key={k.label} onClick={()=>go('shops',{status:k.filter})}><span><k.icon/>{k.label}</span><strong>{k.value}</strong><small>{k.note}</small></button>)}</div>
        <button className="platform-attention" onClick={()=>go('billing')}><span className="platform-attention-icon"><FiCreditCard/></span><span><strong>{data.metrics.pending?data.metrics.pending+' payment'+(data.metrics.pending===1?'':'s')+' to check':'No payments waiting'}</strong><small>{data.metrics.pending?'Check the payment screenshot, then approve or reject the package.':'New bank and Telebirr payments show here.'}</small></span><FiArrowRight/></button>
        <div className="platform-analytics"><section className="owner-card"><div className="owner-card-head"><div><p>SHOP STATUS</p><h3>Where shops stand</h3></div><span className="owner-badge">{data.metrics.shops} total</span></div><StatusChart data={data}/></section><section className="owner-card"><div className="owner-card-head"><div><p>THE LAST SEVEN DAYS</p><h3>New shop signups</h3></div><FiUsers/></div><SignupChart shops={data.shops}/></section></div>
        <section className="owner-card"><div className="owner-card-head"><div><p>PACKAGES IN USE</p><h3>Packages shops chose</h3></div><span className="owner-note">Trials are shown separately</span></div><div className="platform-plan-usage">{data.plans.map(p=>{const shops=data.shops.filter(s=>s.plan_code===p.code),trial=shops.filter(s=>s.access.status==='trial').length,paid=shops.filter(s=>s.access.status==='active').length;return <button key={p.code} onClick={()=>go('shops',{plan:p.code})}><div><strong>{p.name}</strong><span>{paid} paid · {trial} trial · {shops.length-paid-trial} not active</span></div><div className="platform-usage-track"><i style={{width:Math.max(shops.length?3:0,shops.length/Math.max(1,data.metrics.shops)*100)+'%'}}/></div></button>;})}</div><p className="owner-note">Paid packages each month: {amount(data.metrics.recurringRevenue)} at current prices.</p></section>
        <div className="owner-card-head"><div><p>RECENT ARRIVALS</p><h3>Meet your newest shops</h3></div><button className="admin-secondary-button" onClick={()=>go('shops')}>All shops <FiArrowRight/></button></div><div className="platform-subscriber-grid">{data.shops.slice(0,4).map(s=><ShopCard shop={s} key={s.id} review={id=>go('billing',{request:String(id)})} grant={setGrantShop}/>)}</div>{!data.shops.length&&<p className="owner-empty">Your first shop will appear here.</p>}
      </div>}
      {view==='shops'&&data&&<ShopDirectory data={data} params={params} onFilter={(key,value)=>{const next=new URLSearchParams(params);next.set('view','shops');next.delete('shop');value?next.set(key,value):next.delete(key);setParams(next,{replace:true});}} review={id=>go('billing',{request:String(id)})} grant={setGrantShop}/>}
      {view==='billing'&&<PlatformBilling onChange={resource.refresh}/>}
      {view==='packages'&&<PlatformPackages onChange={resource.refresh}/>}
      {view==='messages'&&<PlatformMessages/>}
      {view==='telegram'&&<PlatformTelegram/>}
      {view==='profile'&&<ProfileSettings/>}
    </main>{grantShop&&data&&<ComplimentaryGrant shop={grantShop} plans={data.plans.filter(plan=>plan.active!==false)} onClose={()=>setGrantShop(null)} onGrant={async grant=>{const result=await api.post<{planName:string;durationMonths:number;periodEnd:string}>('/platform/billing/grants',grant);setGrantMessage(`${result.data.planName} granted for ${result.data.durationMonths} month${result.data.durationMonths===1?'':'s'} through ${subscriptionDate(result.data.periodEnd)}.`);await resource.refresh();}}/>}<nav className="platform-bottom-nav" aria-label="Quick platform navigation">{navigation.slice(0,4).map(n=><button className={view===n.id?'is-active':''} key={n.id} onClick={()=>go(n.id)}><n.icon/><span>{n.label}</span></button>)}<button className={view==='telegram'||view==='messages'||view==='profile'?'is-active':''} aria-label="More platform pages" onClick={()=>setSidebar(true)}><FiMenu/><span>More</span></button></nav>
  </div>;
}
function ShopCard({shop:s,review,grant}:{shop:Shop;review:(id:number)=>void;grant:(shop:Shop)=>void}){
  const trial=s.access.status==='trial'||s.access.status==='trial_expired'||s.access.status==='cancelled'&&!s.last_payment&&!s.access.periodEnd&&!!s.trial_ends_at;
  const freeAccess=s.subscription_source==='free_grant'&&s.access.status==='active';
  return <article className="owner-card platform-subscriber"><div className="platform-card-heading"><span className="platform-shop-avatar">{s.name.slice(0,1)}</span><Badge status={s.access.status} source={s.subscription_source}/></div><h3>{s.name}</h3>{s.owners.map((o,i)=><div className="platform-owner" key={i}><strong>{o.name}</strong><a href={'mailto:'+o.email}>{o.email}</a>{o.phone?<a href={'tel:'+o.phone.replace(/[^+0-9]/g,'')}>{o.phone}</a>:<span>Phone not added yet</span>}</div>)}
    <div className="platform-chosen-plan"><small>{trial?'FREE TRIAL':freeAccess?'FREE PACKAGE':'OWNER’S PACKAGE'}</small><strong>{s.plan_name}</strong>{trial&&<span>No paid package yet{s.pending_payment?' · payment being checked':''}</span>}{freeAccess&&<span>Free access from Mirror</span>}{!s.plan_available&&<span>Not offered to new shops</span>}</div>
    <dl className="platform-shop-facts"><div><dt>Joined</dt><dd>{subscriptionDate(s.created_at)}</dd></div><div><dt>Team accounts</dt><dd>{s.staff_count}</dd></div><div><dt>{trial?'Trial ends':freeAccess?'Free package ends':'Paid package ends'}</dt><dd>{subscriptionDate(trial?s.trial_ends_at:s.access.periodEnd)}</dd></div><div><dt>Shop setup</dt><dd>{s.onboarding_completed_at?'Complete':'In progress'}</dd></div>{s.cancelled_at&&<div><dt>Cancelled on</dt><dd>{subscriptionDate(s.cancelled_at)}</dd></div>}</dl>
    {s.access.status==='trial'&&<p className="platform-trial-count"><FiClock/>{s.access.daysRemaining} day{s.access.daysRemaining===1?'':'s'} left in the trial</p>}
    {s.pending_payment&&<div className="platform-pending"><small>PAYMENT WAITING</small><strong>{s.pending_payment.plan_name} · {amount(s.pending_payment.amount)}</strong><button className="admin-secondary-button" onClick={()=>review(s.pending_payment!.id)}>Check payment <FiArrowRight/></button></div>}
    {s.access.status==='trial_expired'&&<div className="platform-card-actions"><button className="admin-primary-button" onClick={()=>grant(s)}>Give free package</button></div>}
  </article>;
}
function ShopDirectory({data,params,onFilter,review,grant}:{data:Data;params:URLSearchParams;onFilter:(key:string,value:string)=>void;review:(id:number)=>void;grant:(shop:Shop)=>void}){
  const search=params.get('q')||'',status=params.get('status')||'all',plan=params.get('plan')||'',id=params.get('shop');
  const shops=data.shops.filter(s=>(!id||String(s.id)===id)&&(!plan||s.plan_code===plan)&&(status==='all'||s.access.status===status||(status==='expired'&&['trial_expired','past_due'].includes(s.access.status))||(status==='pending'&&s.pending_payment))&&[s.name,s.slug,...s.owners.flatMap(o=>[o.name,o.email,o.phone||''])].join(' ').toLowerCase().includes(search.toLowerCase()));
  return <div className="owner-stack"><p className="desk-notice">Owners choose and cancel their own packages. When a free trial ends, you can give a shop a free package for a set time.</p><section className="owner-card platform-filter-bar"><label className="admin-field"><span><FiSearch/> Find a shop or owner</span><input className="admin-input" type="search" value={search} placeholder="Shop, owner or email" onChange={e=>onFilter('q',e.target.value)}/></label><label className="admin-field">Package status<select className="admin-input" value={status} onChange={e=>onFilter('status',e.target.value)}><option value="all">All statuses</option>{Object.entries(statusNames).map(([v,label])=><option key={v} value={v}>{label}</option>)}<option value="expired">All ended</option><option value="pending">Payment waiting</option></select></label><label className="admin-field">Package<select className="admin-input" value={plan} onChange={e=>onFilter('plan',e.target.value)}><option value="">All packages</option>{data.plans.map(p=><option key={p.code} value={p.code}>{p.name}{!p.active?' (not offered)':''}</option>)}</select></label></section><div className="owner-card-head"><h3>{shops.length} shop{shops.length===1?'':'s'}</h3>{id&&<button className="admin-secondary-button" onClick={()=>onFilter('q','')}>Show all shops</button>}</div><div className="platform-subscriber-grid">{shops.map(s=><ShopCard shop={s} key={s.id} review={review} grant={grant}/>)}</div>{!shops.length&&<p className="owner-empty">No shops match these filters.</p>}</div>;
}
function ComplimentaryGrant({shop,plans,onClose,onGrant}:{shop:Shop;plans:SubscriptionPlan[];onClose:()=>void;onGrant:(grant:{shopId:number;planCode:string;durationMonths:number;note:string})=>Promise<void>}){
  const [planCode,setPlanCode]=useState(plans.find(plan=>plan.code===shop.plan_code)?.code||plans[0]?.code||'');
  const [durationMonths,setDurationMonths]=useState(1),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{await onGrant({shopId:shop.id,planCode,durationMonths,note});onClose();}catch(cause){setError(cause instanceof Error?cause.message:'Could not grant access.');}finally{setBusy(false);}};
  return <DeskModal title="Give free package" busy={busy} onClose={onClose}><form className="desk-form" onSubmit={submit}><div className="desk-notice"><strong>{shop.name}</strong><br/>Their 7-day free trial has ended. This turns on the package without payment.</div><label className="admin-field">Package<select className="admin-input" required value={planCode} onChange={event=>setPlanCode(event.target.value)}>{plans.map(plan=><option value={plan.code} key={plan.code}>{plan.name}</option>)}</select></label><label className="admin-field">Free time<select className="admin-input" value={durationMonths} onChange={event=>setDurationMonths(Number(event.target.value))}><option value={1}>1 month</option><option value={3}>3 months</option><option value={6}>6 months</option><option value={12}>1 year</option></select></label><label className="admin-field">Note for the owner <small>Optional</small><textarea className="admin-input" maxLength={500} value={note} onChange={event=>setNote(event.target.value)} placeholder="e.g. Welcome gift"/></label>{error&&<p className="admin-inline-error" role="alert">{error}</p>}<button className="admin-primary-button" disabled={busy||!planCode}>{busy?'Saving…':'Turn on free package'}</button></form></DeskModal>;
}
function StatusChart({data}:{data:Data}){
  const m=data.metrics,rows=[{label:'Paid & active',n:m.active,color:'#7760db'},{label:'Free trial',n:m.trial,color:'#62b7ab'},{label:'Cancelled',n:m.cancelled,color:'#e9a786'},{label:'Ended',n:m.expired,color:'#c8bdde'},{label:'Paused',n:m.shops-m.active-m.trial-m.cancelled-m.expired,color:'#8b90a0'}].filter(r=>r.n>0);
  let stop=0;const gradient=rows.map(r=>{const start=stop;stop+=r.n/Math.max(m.shops,1)*100;return r.color+' '+start+'% '+stop+'%';}).join(',');
  return <div className="platform-health"><div className="platform-donut" role="img" aria-label={rows.map(r=>r.label+': '+r.n).join(', ')||'No shops yet'} style={{background:rows.length?'conic-gradient('+gradient+')':'#edeaf5'}}><div><strong>{m.shops}</strong><span>shops</span></div></div><div className="platform-chart-legend">{rows.map(r=><div key={r.label}><i style={{background:r.color}}/><span>{r.label}</span><strong>{r.n}</strong></div>)}{!rows.length&&<p>Your community starts here.</p>}</div></div>;
}
function SignupChart({shops}:{shops:Shop[]}){
  const days=Array.from({length:7},(_,i)=>{const day=new Date();day.setDate(day.getDate()-6+i);const key=day.toLocaleDateString('en-CA');return {label:day.toLocaleDateString('en-GB',{weekday:'short'}),n:shops.filter(s=>new Date(s.created_at).toLocaleDateString('en-CA')===key).length};});
  const max=Math.max(1,...days.map(d=>d.n));
  return <div className="platform-signup-chart" role="img" aria-label={'New shops: '+days.map(d=>d.label+' '+d.n).join(', ')}>{days.map(d=><div key={d.label}><div className="platform-signup-bar"><i style={{height:Math.max(d.n?8:2,d.n/max*100)+'%'}}><b>{d.n}</b></i></div><span>{d.label}</span></div>)}</div>;
}
