import {useState} from 'react';
import {Link} from 'react-router-dom';
import {FiArrowRight,FiCheck,FiScissors,FiMenu,FiX,FiUsers,FiCreditCard,FiBarChart2,FiSmartphone,FiSend,FiCheckCircle,FiTrendingUp,FiZap,FiPhone,FiMessageCircle,FiMail} from 'react-icons/fi';
import {useDeskResource} from '../../../Components/Reception/desk';
import {planContents} from '../../../config/plans';
import type {SubscriptionPlan} from '../../../config/subscription';
const inclusivePlanDescription=(description:string)=>description.replace(/\bbarbershops\b/gi,'salons and shops').replace(/\bbarbershop\b/gi,'salon or shop');
const platformSupport={phone:'+251 910 767664',email:'devagirma@gmail.com',telegram:'https://t.me/+251910767664',whatsapp:'https://wa.me/251910767664'};
export default function PlatformHome(){
  const [menu,setMenu]=useState(false);
  const plans=useDeskResource<SubscriptionPlan[]>('/public/plans',0);
  return <div className="saas-site">
    <a className="saas-skip" href="#main-content">Go to main page</a>
    <header className="saas-nav saas-container"><Link className="saas-brand saas-brand-mirror" to="/" aria-label="Mirror"><img src="/mirror.svg" alt=""/><b>Mirror</b></Link><nav className={menu?'is-open':''} aria-label="Main menu"><a href="#how-it-works" onClick={()=>setMenu(false)}>How to use</a><a href="#pricing" onClick={()=>setMenu(false)}>Packages</a><a href="#questions" onClick={()=>setMenu(false)}>Help</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a><Link to="/login">Sign in</Link></nav><Link className="saas-button saas-nav-cta" to="/signup">Try free <FiArrowRight/></Link><button className="saas-menu" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<FiX/>:<FiMenu/>}</button></header>
    <main id="main-content">
      <section className="saas-hero-shell"><div className="saas-hero saas-container"><div className="saas-hero-copy"><span className="saas-hero-kicker"><i/><span>Try first. Pay later.</span><b>7 days free</b></span><h1>See Your Salon<br/><em>Clearly.</em></h1><p>One simple place for customers, payments, stock, and staff.</p><div className="saas-hero-actions"><Link className="saas-button saas-hero-button" to="/signup">Start 7 days free <FiArrowRight/></Link><a className="saas-text-link" href="#how-it-works">How it works <span>↗</span></a></div></div>
        <div className="saas-preview-wrap"><i className="saas-preview-orbit one"/><i className="saas-preview-orbit two"/><div className="saas-preview"><div className="saas-preview-top"><strong><FiScissors/> Your shop</strong><span className="saas-preview-live"><i/> Live day</span></div><div className="saas-preview-body"><div className="saas-preview-greeting"><div><small>EVERYTHING IN ONE PLACE</small><h2>A good day at the shop.</h2></div><span>Today ↗</span></div><div className="saas-preview-stats"><div><span>Today’s sales</span><strong>ETB 4,800</strong><small>24 customers served</small></div><div><span>Expenses</span><strong>ETB 620</strong><small>Recorded and accounted for</small></div></div><div className="saas-preview-chart"><div><strong>Your week at a glance</strong><span>Sales <i/> Expenses</span></div><svg viewBox="0 0 440 120" role="img" aria-label="Illustration of a shop's weekly sales trend"><defs><linearGradient id="preview-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#7c6df0" stopOpacity=".3"/><stop offset="1" stopColor="#7c6df0" stopOpacity="0"/></linearGradient></defs><path d="M0 90 Q30 86 55 66 T110 75 T170 44 T230 51 T290 29 T350 38 T410 12 L440 5 L440 120 L0 120Z" fill="url(#preview-fill)"/><path d="M0 90 Q30 86 55 66 T110 75 T170 44 T230 51 T290 29 T350 38 T410 12 L440 5" fill="none" stroke="#7262df" strokeWidth="3"/><path d="M0 107 L60 98 L125 108 L190 92 L260 102 L320 88 L380 100 L440 90" fill="none" stroke="#dba669" strokeWidth="2"/></svg><div className="saas-chart-days">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><span key={d}>{d}</span>)}</div></div><div className="saas-preview-team"><span className="saas-avatar">A</span><div><strong>Abel’s customer</strong><small>Haircut + beard trim</small></div><span className="saas-preview-paid"><FiCheckCircle/> Paid</span></div></div><div className="saas-preview-caption">PRODUCT PREVIEW · ILLUSTRATIVE DATA</div></div><div className="saas-floating-note"><FiSend/><div><strong>Your daily digest is ready.</strong><span>Sales, customers, expenses & low stock.</span></div></div><div className="saas-floating-payment"><span><FiTrendingUp/></span><div><small>COLLECTIONS TODAY</small><strong>ETB 4,800 recorded</strong><em>Cash · Telebirr · Bank</em></div></div></div>
      </div></section>
      <section className="saas-trial-journey saas-container" aria-label="Your free trial"><div><span className="saas-eyebrow">YOUR SHOP. YOUR DAILY WORK.</span><h2>Set up today. Try before you pay.</h2><p>Add your staff, services, and payment accounts. Then use it in your shop.</p></div><ol><li><span>01</span><div><strong>Create your shop</strong><small>Just a few details</small></div></li><li><span>02</span><div><strong>Add your staff</strong><small>Reception and stylists</small></div></li><li><span>03</span><div><strong>Use it every day</strong><small>Pay only if you continue</small></div></li></ol></section>
      <div className="saas-ribbon"><div className="saas-container"><span>Made for the rhythm of a real shop.</span><strong><FiUsers/> Walk-in first</strong><strong><FiCreditCard/> Cash, bank & Telebirr</strong><strong><FiSmartphone/> Made for mobile</strong></div></div>
      <section id="how-it-works" className="saas-section saas-container"><div className="saas-section-heading"><span className="saas-eyebrow">YOUR DAILY WORK, MADE SIMPLE.</span><h2>Three steps.<br/>Easy to follow.</h2><p>Your team keeps its normal way of working.</p></div><div className="saas-flow saas-day-flow">{[
        ['01','Assign','Reception sends the walk-in to the stylist they choose.',FiUsers],
        ['02','Collect','Take cash, bank, or Telebirr payment after service.',FiCreditCard],
        ['03','Close','See sales, expenses, and stock at the end of the day.',FiBarChart2],
      ].map(([n,title,description,Icon])=><article key={String(n)}><div><span>{String(n)}</span><Icon/></div><h3>{String(title)}</h3><p>{String(description)}</p></article>)}</div></section>
      <section className="saas-role-section-tinted"><div className="saas-container saas-role-section"><div className="saas-section-heading"><span className="saas-eyebrow">ONE SHOP. THREE SIMPLE PAGES.</span><h2>Each person sees their own work.</h2><p>Everyone signs in with their own phone or email and password.</p><Link to="/signup" className="saas-text-link">Set up my shop <FiArrowRight/></Link></div><div className="saas-role-list"><article><span>01</span><div><h3>Owner</h3><p>Money, staff, and reports.</p></div></article><article><span>02</span><div><h3>Reception</h3><p>Walk-ins, payments, and closing the day.</p></div></article><article><span>03</span><div><h3>Stylist</h3><p>Customers and earnings.</p></div></article></div></div></section>
      <section id="pricing" className="saas-section saas-pricing saas-container"><div className="saas-section-heading"><span className="saas-eyebrow">TRY FIRST. PAY LATER.</span><h2>Use it free for seven days.</h2><p>Choose a package only when you want to continue.</p></div>
        {plans.error&&<p role="alert">Packages are temporarily unavailable. <button onClick={plans.refresh}>Try again</button></p>}
        {plans.loading&&<p>Loading packages…</p>}
        <div className="saas-plan-grid">{plans.data?.map(plan=><article className={'saas-plan '+(plan.tier!=='basic'?'is-plus':'')} key={plan.code}>{plan.tier==='max'&&<span className="saas-plan-badge"><FiZap/> No daily limit</span>}<span className="saas-eyebrow">{plan.tier==='max'?'FOR BUSY SHOPS':plan.tier==='plus'?'FOR GROWING SHOPS':'FOR SMALL SHOPS'}</span><h3>{plan.name}</h3><p>{inclusivePlanDescription(plan.description)}</p><div className="saas-plan-price">ETB <strong>{Number(plan.monthly_price).toLocaleString()}</strong><span>/ month</span></div><Link className={plan.tier!=='basic'?'saas-button':'saas-button saas-button-light'} to="/signup">Start free — no payment <FiArrowRight/></Link><ul>{planContents(plan).map((item,i)=><li key={i}><FiCheck/>{item}</li>)}</ul>{plan.tier==='max'&&<small>After payment, the platform team contacts you directly to discuss website and online booking support.</small>}</article>)}</div>
        <p className="saas-pricing-note">No payment today. After seven days, pay by bank transfer or Telebirr only if you want to continue.</p></section>
      <section id="questions" className="saas-section saas-container saas-faq"><div className="saas-section-heading"><span className="saas-eyebrow">HELP</span><h2>Common questions.</h2></div><div>{[
        ['What happens after seven days?','Choose a package and pay by bank transfer or Telebirr if you want to continue. Your records stay saved.'],
        ['Do I pay to start?','No. The free trial needs no payment and has no automatic charge.'],
        ['What do I need first?','Create your shop, add your staff and services, then use it as normal.'],
      ].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
      <section id="contact" className="saas-contact saas-container"><div className="saas-contact-copy"><span className="saas-eyebrow">WE CAN HELP</span><h2>Do you have a question?</h2><p>Talk to the Mirror platform admin before you start or choose a package.</p></div><div className="saas-contact-actions"><a className="saas-contact-card is-phone" href={'tel:'+platformSupport.phone.replace(/[^+0-9]/g,'')}><FiPhone/><span><small>CALL</small><strong>{platformSupport.phone}</strong></span><FiArrowRight/></a><a className="saas-contact-card is-whatsapp" href={platformSupport.whatsapp} target="_blank" rel="noreferrer"><FiMessageCircle/><span><small>WHATSAPP</small><strong>Chat with us</strong></span><FiArrowRight/></a><a className="saas-contact-card is-telegram" href={platformSupport.telegram} target="_blank" rel="noreferrer"><FiSend/><span><small>TELEGRAM</small><strong>Message us</strong></span><FiArrowRight/></a><a className="saas-contact-card is-email" href={'mailto:'+platformSupport.email}><FiMail/><span><small>EMAIL</small><strong>{platformSupport.email}</strong></span><FiArrowRight/></a></div></section>
      <section className="saas-bottom-cta saas-container"><span className="saas-tag"><i/> TRY FIRST. PAY LATER.</span><h2>Try it with your own shop.</h2><p>Use Mirror free for seven days, then decide.</p><Link className="saas-button" to="/signup">Create my shop — 7 days free <FiArrowRight/></Link><small><FiCheckCircle/> No payment today. No automatic charge.</small></section>
    </main><footer className="saas-footer saas-container"><Link className="saas-brand saas-brand-mirror" to="/" aria-label="Mirror — see your salon clearly"><img src="/mirror.svg" alt=""/><b>Mirror</b></Link><p>Mirror — see your salon clearly.</p><div><a href="#pricing">Packages</a><a href="#contact">Contact</a><Link to="/login">Sign in</Link><Link to="/signup">Get started</Link></div><small>Platform contact · <a href={'mailto:'+platformSupport.email}>{platformSupport.email}</a> · <a href={'tel:'+platformSupport.phone.replace(/[^+0-9]/g,'')}>{platformSupport.phone}</a></small><small>© {new Date().getFullYear()} Mirror</small></footer>
  </div>;
}
