import {useEffect,useState,type CSSProperties} from 'react';
import {Link,useParams} from 'react-router-dom';
import {FiArrowRight,FiMapPin,FiPhone} from 'react-icons/fi';
import api,{API_URL} from '../../../api/axios';
export default function ShopPage(){
  const {shopSlug}=useParams();const [data,setData]=useState<any>(null),[error,setError]=useState('');
  const websiteDomain=String(import.meta.env.VITE_PUBLIC_WEBSITE_DOMAIN||'').trim().toLowerCase().replace(/^https?:\/\//,'').replace(/\/$/,'');
  const host=window.location.hostname.toLowerCase(),suffix=websiteDomain?`.${websiteDomain}`:'';
  const hostSubdomain=!shopSlug&&suffix&&host.endsWith(suffix)?host.slice(0,-suffix.length):'';
  useEffect(()=>{let active=true;setData(null);setError('');const params=shopSlug?{shop:shopSlug}:{subdomain:hostSubdomain};if(!shopSlug&&!hostSubdomain){setError('This shop page is not available now.');return()=>{active=false;};}api.get('/public/shop',{params}).then(shop=>Promise.all([Promise.resolve(shop),api.get('/services',{params:{shop:shop.data.slug}}),api.get('/barber/barbers',{params:{shop:shop.data.slug}})])).then(([shop,services,barbers])=>{if(active)setData({shop:shop.data,services:services.data,barbers:barbers.data});}).catch(()=>{if(active)setError('This shop page is not available now. Please contact the shop directly.');});return()=>{active=false;};},[shopSlug,hostSubdomain]);
  if(!data)return <main className="saas-access-state"><img src="/mirror.svg" alt=""/><p>{error||'Loading this shop…'}</p><Link to="/">About Mirror</Link></main>;
  if(!data.shop.features.publicWebsite)return <main className="saas-access-state"><p>This shop website is not enabled.</p><Link to="/">About Mirror</Link></main>;
  const {shop,services,barbers}=data,booking=shopSlug?`/s/${shopSlug}/booking`:`/booking?shop=${encodeURIComponent(shop.slug)}`,website=shop.website||{};
  const colours:Record<string,string>={plum:'#6854d8',ocean:'#2378a7',sage:'#39846e',gold:'#a87535'};
  const accent=colours[website.palette]||'#6854d8',assets=website.assets||[],logo=assets.find((asset:any)=>asset.kind==='logo'),photos=assets.filter((asset:any)=>asset.kind==='shop_photo');
  const siteStyle={'--accent':accent} as CSSProperties,template=website.templateCode||'studio',sitePath=shopSlug?`/s/${shopSlug}`:'/';
  return <div className={`saas-site shop-public-page shop-template-${template} shop-theme-${website.theme||'light'}`} style={siteStyle}><header className="saas-nav saas-container"><Link className="saas-brand" to={sitePath}>{logo?<img className="shop-public-logo" src={API_URL+logo.filePath} alt={`${shop.name} logo`}/>:<img className="shop-public-logo" src="/mirror.svg" alt=""/>}{shop.name}</Link><Link className="saas-button" to={booking}>Book a visit</Link></header><main><section className="saas-hero saas-container shop-public-hero"><div><span className="saas-eyebrow">WELCOME TO {shop.name}</span><h1>{website.heroTitle||'Your stylist. Your style.'}</h1><p>{website.introduction||'Visit your regular stylist or book your next service. Walk-ins are welcome.'}</p><div className="saas-hero-actions"><Link className="saas-button" to={booking}>{website.primaryGoal==='showcase'?'Explore services':'Book a visit'} <FiArrowRight/></Link></div></div>{photos[0]?<img className="shop-public-hero-image" src={API_URL+photos[0].filePath} alt={`${shop.name} interior`}/>:<div className="saas-plan"><h2>Find us</h2>{shop.address&&<p><FiMapPin/> {shop.address}</p>}{shop.phone&&<p><FiPhone/> <a href={`tel:${shop.phone}`}>{shop.phone}</a></p>}<p>Choose your service below and pay at reception after your visit.</p></div>}</section><section className="saas-section saas-container"><div className="saas-section-heading"><span className="saas-eyebrow">THE SERVICE MENU</span><h2>A little time for yourself.</h2></div><div className="saas-benefit-grid">{services.map((s:any)=><article key={s.id}><h3>{s.name}</h3><p>{shop.currency} {Number(s.price).toLocaleString()} · {s.duration} min</p><Link to={booking} className="saas-text-link">Book this service <FiArrowRight/></Link></article>)}</div></section>{photos.length>1&&<section className="saas-section saas-container"><div className="saas-section-heading"><span className="saas-eyebrow">INSIDE THE SHOP</span><h2>Made to feel good.</h2></div><div className="shop-public-gallery">{photos.slice(1).map((photo:any,index:number)=><img key={index} src={API_URL+photo.filePath} alt={`${shop.name} space ${index+2}`}/>)}</div></section>}<section className="saas-section saas-container"><div className="saas-section-heading"><h2>Meet your stylists.</h2></div><div className="saas-flow">{barbers.map((b:any)=><article key={b.id}>{b.profile_picture&&<img src={b.profile_picture.startsWith('/')?API_URL+b.profile_picture:b.profile_picture} alt={b.name} style={{width:80,height:80,objectFit:'cover',borderRadius:16,marginBottom:18}}/>}<h3>{b.name}</h3><Link to={booking} className="saas-text-link">Book a visit <FiArrowRight/></Link></article>)}</div></section></main><footer className="saas-footer saas-container"><strong>{shop.name}</strong>{website.instagram&&<span>{website.instagram}</span>}<Link to="/">Powered by Mirror</Link></footer></div>;
}
